### ISSUE TITLE
Incohérences des heures (timetable)

### ISSUE THREAD

**Issue by Ryzzzen** [Litarvan/pronote-api#10]
Dans les données reçues de l'emploi du temps, les cours n'ont pas les bonnes heures, et je n'arrive pas à trouver un motif ou quelque chose pour comprendre:

- Par exemple, mon premier cours commence à 8h et se termine à 11h. D'après l'API, les timestamp étant respectivement de `1578290400000 `à `1578312000000`; soit avec la méthode `toISOString()`, on obtient respectivement `2020-01-06T06:00:00.000Z`, et `2020-01-06T12:00:00.000Z`; donc d'après l'API mon cours commencerait à 6h et se terminerait à 12h.

J'avais plusieurs hypothèses, d'abord peut-être que les timestamp commencent toujours à 6h mais il faut regarder que l'écart entre les deux dates (from/to), parce que sur mon emploi du temps Pronote même si on à pas de cours à ces heures-ci l'emploi du temps affiche les cours de 6 heures à 22 heures; mais dans ce cas-là pourquoi jusqu'à midi?

De plus mon cours dure trois heures, pas quatre. Encore plus étrange. Ce qui disqualifie aussi une autre hypothèse que j'avais; les heures d'été/d'hiver ou quoi.

Le même problème apparaît aussi par exemple dans le cours d'après, selon l'API le cours commence à 9h et se terminerait à 11h, alors qu'il commence à 11h et se termine à midi.

![image](https://user-images.githubusercontent.com/5779685/71426652-24fd5000-26ad-11ea-82a1-524b6b3523da.png)

J'utilise le CAS ac-toulouse. En espérant que vous ayez une idée. Merci d'avance!

**Comment by Litarvan** [comment]
Salut ! Jvais faire de mon mieux pour essayer de débugger ça à distance.
Faudrait que tu rajoutes ça dans src/pronote.js à la ligne 658 :
```js
const fs = require('fs');
if (!fs.existsSync('timetable.json') && result.length > 0) {
    fs.writeFileSync('timetable.json', JSON.stringify(timetable.donnees.ListeCours, null, 4));
    fs.writeFileSync('timetable.result.json', JSON.stringify(result, null, 4));
    fs.writeFileSync('timetable.checked.json', JSON.stringify(checked, null, 4));
}
```
Ensuite tu peux retester et trois fichiers .json devraient pop, tu peux me les envoyer (sur ton commentaire directement) et ça devrait me permettre de debug ça

**Comment by Ryzzzen** [comment]
[Voilà les fichiers.](https://github.com/Litarvan/pronote-api/files/4002777/results.zip). J'ai regardé un peu, dans `timetable.json`, les dates ont l'air correctes (j'ai juste regardé les variables `DateDuCours.V
). C'est après le traitement des données (soit `timetable.result.json`), que les dates ne sont plus bonnes.

**Comment by Litarvan** [comment]
Tiens mais c'est bizarre, ça me fait limite poser la question de pourquoi ça marchait avant (et le code que t'as changé avait l'air horrible), je vais tout de suite voir ça chez quelqu'un d'autre.

**Comment by Litarvan** [comment]
Eh bien ça ne marche pas non plus chez les autres (alors qu'avec ton code si), visiblement Pronote ont changé la valeur du field "durée" vu qu'avant c'était nombre de demi heure - 1 (d'où mon code dégueu qui était en fait la bonne méthode xD), mais c'est ouf que je l'ai pas remarqué avant O_o, j'espère que ça va pas casser des trucs (au pire on verra kappa)

**Comment by Litarvan** [comment]
Tiens j'avais pas vu que t'avais rajouté d'autres trucs sur ton fork, c'est cool tu peux PR tout ça stuveux (déso j'ai réglé aussi de mon côté le truc des offsets de temps donc t'auras un mini conflit quand tu vas rebase), faudrait juste refractor le code en double dans index.js/server.js

**Comment by Litarvan** [comment]
Je relance un peu mais j'ai trouvé le problème @Ryzzzen et c'est réglé pour de bon dans la V2 pour tous les établissements
