### ISSUE TITLE
Ajouter un nouveau CAS

### ISSUE THREAD

**Issue by Shadowv7** [Litarvan/pronote-api#101]
Ajouter le CAS ac-reunion

**Comment by trmaud** [comment]
Oui, mais pour cela il nous faut des infos 
(Lien de l'ent)

Cdt
Thibaut

**Comment by Shadowv7** [comment]
http://metice.ac-reunion.fr/

**Comment by andronedev** [comment]
Salut !, possible d'ajouter le CAS  cas.mon-ent-occitanie.fr/ ?
