### ISSUE TITLE
Cannot return null for non-nullable field LessonContent.title

### ISSUE THREAD

**Issue by MAXOUXAX** [Litarvan/pronote-api#102]
Hello, j'ai un problème et je pense qu'il serait plus judicieux de "régler" ça de votre côté.
J'utilise le serveur GQL, et lorsque j'effectue cette query:
`{contents(from: \""+date+"\") {from to subject teachers color title description}}` et qu'un cours ne possède pas de titre, j'obtiens cette erreur:
`{"data":{"contents":null},"errors":[{"path":["contents",1,"title"],"locations":[{"line":1,"column":63}],"message":"Cannot return null for non-nullable field LessonContent.title."}]}`

Elle est assez explicite, mais le problème est que SI je veux pouvoir récupérer le contenu des cours sans avoir cette erreur, il faudrait que j'effectue ma requête, regarde si une erreur est survenue, et si oui retirer le field posant problème, puis effectuer à nouveau ma requête, mais c'est vraiment pas pratique.

Je pense qu'il serait plus judicieux de régler ce problème en faisant en sorte que le champ title soit nullable (puisque visiblement Pronote permet aux professeurs de ne pas remplir ce champ).

**Comment by trmaud** [comment]
Hello,

Je viens de verifier, mais normalement l'api contient déjà l'exeption du nullable.

Cdt
Thibaut

**Comment by MAXOUXAX** [comment]
Pourtant j'obtiens bel et bien une erreur, et la requête fonctionne si je retire le field title.

**Comment by Litarvan** [comment]
Effectivement, c'est fix sur master
