### ISSUE TITLE
Récupération de l'ID temporaire pour les devoirs (N)

### ISSUE THREAD

**Issue by Androz2091** [Litarvan/pronote-api#104]
Bonjour :wave:
Je suis en train de bosser sur un projet qui permettrait de recevoir des notifications via Insta lorsqu'un devoir ou un cours est ajouté, modifié ou supprimé.

Actuellement, j'ai commencé à stocker la liste des devoirs pour chaque élève, et je compare simplement le tableau dans la db (qui me sert de cache) et le tableau récupéré via la lib. S'il y a une différence, j'envoie une notification.

Ça fonctionne, mais je me suis penché un peu plus sur les données retournées via Pronote (en bas niveau donc) `/src/fetch/pronote/homeworks.js`. Est-ce que vous savez à quoi correspond la propriété `N` ? J'ai l'impression que c'est un ID "temporaire" (il ne change que si la session est détruite et de nouveau créée). Si c'est le cas, ça pourrait m'être assez utile, si un devoir est modifié par exemple ça me permettrait d'identifier de manière plus sure quel était l'ancien devoir (actuellement si deux devoirs changent en même temps... c'est compliqué). Si vous avez plus d'infos là dessus ça m'intéresserait (est-ce que cet ID change quand même si le devoir est modifié ?, est-ce que vous l'utilisez déjà pour un projet ?)

Merci

**Comment by trmaud** [comment]
@Androz2091 Alors cela n'est pas sur, mais je te confirm que si tu reste sur la même session il reste avec le même id.
Par contre de souvenir en cas de modification, c'est comme si Pronote supprimais et recrée un nouveaux devoir.  donc l'id changeais quoi qu'il arrive.

Cdt
Thibaut

**Comment by Androz2091** [comment]
> Par contre de souvenir en cas de modification, c'est comme si Pronote supprimais et recrée un nouveaux devoir. donc l'id changeais quoi qu'il arrive.

Ok, c'est bien ce que je me disais... Alors ça n'a pas vraiment d'intérêt de le récupérer 🤔 
Je testerai ça quand je pourrai, mais comme je n'ai pas de serveur pronote et que la modification d'un devoir arrive relativement rarement ça va être compliqué 😅

**Comment by trmaud** [comment]
@Androz2091 regarded, tu a une license d'essait de 15 jours de souvenir.

Cdt
Thibaut

**Comment by trmaud** [comment]
Pardon, je change, il l'on virée pour mettre que EDT en version de test.

Cdt
Thibaut

**Comment by trmaud** [comment]
Nouveaux commentaire : j'ai trouvé sa, je test pour te dire ce que l'on peux faire avec ;) 

https://www.index-education.com/fr/faq-pronote-single-5630-quelles-applications-dois-je-telecharger-.php

Cdt
Thibaut

**Comment by Litarvan** [comment]
L'ID change à chaque session, ce qui lui enlève sa seule possible utilité qui est celle de vérifier l'unicité d'un devoir entre chaque requête. C'est pour ça qu'on l'envoie pas. Je prévois d'ajouter un ID généré par l'API pour chacun de ces objets, via un hash des données importantes, faut voir ce que ça donne.
