### ISSUE TITLE
information de connexions

### ISSUE THREAD

**Issue by FlorianPasDidee** [Litarvan/pronote-api#105]
Bonjour,

je voudrai savoir où avoir le lien de pronote et où mettre le CAS si il y en a besoin (je suis à l'ac-rouen)

merci de votre réponse

**Comment by Androz2091** [comment]
Bonjour,

Une fois sur Pronote tu peux simplement copier coller l'URL sur laquelle tu es. Elle devrait ressembler à ça: https://0310047h.index-education.net/pronote/. 

Pour le CAS, c'est le 3ème paramètre de la fonction login:
```js
const session = await pronote.login('https://0310047h.index-education.net/pronote/', 'username', 'password', 'ac-rouen');
```
