### ISSUE TITLE
'Session has expired due to inactivity or error'

### ISSUE THREAD

**Issue by Aperre** [Litarvan/pronote-api#106]
Je suis un eleve qui essay de faire un petit code d'experimentation mais malheureusement je n'arrive pas a me connecter. Quand je tourne le code. La console print 
`code: 5, message: 'Session has expired due to inactivity or error'`
J'ai esseyer avec le site demo sa a marcher mais pas mon etablissement 3500057k.index-education.net/pronote/eleve.html

**Comment by trmaud** [comment]
Hello,
Tu met exactement le lien que tu nous a mis dans ta demande ?
Ou tu met un autre paramètres ?

Cdt
Thibaut

**Comment by ThibautTrarbach** [comment]
Pas de réponse, je te laisse rouvrir quand tu repasse.

Cdt
Thibaut

**Comment by Aperre** [comment]
Oui pardon. Le lien c'est le lien du pronote discord et pour la version j'utilise NPM " https://3500057k.index-education.net/pronote/eleve.html " Lien de l'ecole.

**Comment by ThibautTrarbach** [comment]
Ok,

Tu utilise quel cas avec ?

Cdt
thibaut

**Comment by Aperre** [comment]
Aucun.

**Comment by ThibautTrarbach** [comment]
Ok tu a test avec ce lien ? : "https://3500057k.index-education.net/pronote/"

Cdt
Thibaut

**Comment by Aperre** [comment]
Comme CAS?

**Comment by Aperre** [comment]
Pour mon code il est ici "https://repl.it/@Aperre/pronote#index.js" Je ne crois pas savoir le probleme.

**Comment by Aperre** [comment]
Quelle est le probleme?

**Comment by ThibautTrarbach** [comment]
Hello,

Je vois aucuns problèmes dans ce code.

Tu a plus de logs ou pas ?

Cdt
Thibaut

**Comment by Litarvan** [comment]
Salut, il n'y a effectivement pas l'air d'avoir de problème dans le code... l'erreur que tu as arrive soit quand la session a expiré soit quand il y a eu une erreur de communication entre l'API et le serveur (ce qui est sûrement le cas ici). Est-ce que tu peux essayer de voir à quelle ligne l'erreur est lâchée ?

**Comment by busybox11** [comment]
J'ai aussi souvent ce genre d'erreur que j'ai remarqué avec le debugger. Lorsque ça se reproduira, je posterais mon problème ici (si j'y pense).

**Comment by busybox11** [comment]
Here I am.
![image](https://user-images.githubusercontent.com/29630035/95364469-23fe7d80-08d1-11eb-983a-3f02c3ef62b5.png)

**Comment by busybox11** [comment]
Bon, j'ai toujours le même problème, que ce soit sur le serveur de test de Pronote ou sur celui de mon lycée (je n'en ai pas d'autres pour tester).

Est-ce qu'il y a quelque chose à faire ?

![image](https://user-images.githubusercontent.com/29630035/95508182-e40fc700-09b2-11eb-8acd-8c7ef86919fc.png)

**Comment by Aperre** [comment]
a
`const session = await pronote.login(url, username, password);`
le code ne marche pas

**Comment by Aperre** [comment]
Pour spécifier mon ecole utilise le pronote ancien 
![image](https://user-images.githubusercontent.com/60411288/95718391-49d7a980-0c66-11eb-99eb-7721f4b1f165.png)

**Comment by ThibautTrarbach** [comment]
@Aperre Je me suis permis de delete tes message, car cela a rien a voir avec le sujet actuel.

Cdt
Thibaut

**Comment by Litarvan** [comment]
Réglé en privé
