### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by Maxim-Costa** [Litarvan/pronote-api#110]
{
    "err": {
        "message": "unable to verify the first certificate",
        "name": "Error",
        "stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket._finishInit (_tls_wrap.js:936:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12)",
        "config": {
            "url": "https://0340040j.index-education.net/pronote/eleve.html?login=true",
            "method": "get",
            "headers": {
                "Accept": "application/json, text/plain, */*",
                "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0",
                "Content-Type": "",
                "Cookie": ""
            },
            "transformRequest": [
                null
            ],
            "transformResponse": [
                null
            ],
            "timeout": 0,
            "xsrfCookieName": "XSRF-TOKEN",
            "xsrfHeaderName": "X-XSRF-TOKEN",
            "maxContentLength": -1,
            "maxRedirects": 0
        },
        "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
    }
}

Utilisé avec NodeJS marche dans certains cas mais pour https://0340040j.index-education.net/pronote/ ça ne fonctionne pas

**Comment by ThibautTrarbach** [comment]
Hello,
Tu en est ou ?

Tu a un peux plus d'info ?

Cdt
Thibaut

**Comment by Litarvan** [comment]
Ca ne vient pas de l'API mais de Node.JS ou du serveur Pronote. Essaie de mettre à jour ton système et Node.JS, et de vérifier si ton PC est à l'heure, sinon cherche la solution de cette erreur pour Node.JS

**Comment by Maxim-Costa** [comment]
Okay je vais regarder
