### ISSUE TITLE
Exécuter deux requêtes simultanément ne fonctionne pas

### ISSUE THREAD

**Issue by Androz2091** [Litarvan/pronote-api#112]
La librairie ne prend pas en charge le fait que deux méthodes puissent être appelées simultanément. J'imagine que cela est dû au `session.request` qui est mis à jour deux fois (pour les deux requêtes) avant que la première requête ait été effectuée. Je peux proposer une solution via une PR mais si quelqu'un s'y connait plus ce serait top.

**Comment by ThibautTrarbach** [comment]
Hello,

Vu la non réponse de @Litarvan, tu peux faire un PR. Je le pousserait et je le testerait si besoin.


Cdt
Thibaut

**Comment by Androz2091** [comment]
Ok, ça marche, je verrai si je peux faire ça. De toute façon, j'envoie un message ici quand je m'y mets donc si quelqu'un voit ça avant et souhaite le faire pas de problème 👍

**Comment by Litarvan** [comment]
Hello hello désolé je suis pas torp dispo en ce moment, mais tu peux envoyer un code permettant de reproduire ? J'ai du mal à comprendre comment ça peut arriver

**Comment by Litarvan** [comment]
Réglé en privé
