### ISSUE TITLE
Salut !, possible d'ajouter le CAS  cas.mon-ent-occitanie.fr/ ?

### ISSUE THREAD

**Issue by ThibautTrarbach** [Litarvan/pronote-api#115]
Salut !, possible d'ajouter le CAS  cas.mon-ent-occitanie.fr/ ?

_Originally posted by @andronedev in https://github.com/Litarvan/pronote-api/issues/101#issuecomment-701373713_

**Comment by ThibautTrarbach** [comment]
Hello,

J'ai crée une issue dédier plutôt que de polluer celle de quelqu'un d'autre.

Ps : Ton ent est déjà compatible sur le cas de Montpelier.

Cdt
Thibaut

**Comment by Androz2091** [comment]
Il est aussi déjà compatible pour Toulouse, j'utilise cette URL pour mes tests
