### ISSUE TITLE
Undefined error dans l'académie de Dijon

### ISSUE THREAD

**Issue by Osaxely** [Litarvan/pronote-api#116]
Bonjour !
J'ai modifié un peu le paquet distribué pour y rajouter l'académie de Dijon (car elle sur sur github mais pas dans le paquet), mais quand j'exécute le code avec les bon identifiants, j'obtiens l'erreur 'undefined'
Est-ce que cela serait du au fait que l'académie de Dijon n'est pas encore stable dans l'API, ou autre chose ?
Bonne soirée ! :)

**Comment by ThibautTrarbach** [comment]
Hello,

C'est surement du car tu a oublier des param ou alors que tu a pas la bonne version des autre fichier dependant

Cdt
thibaut

**Comment by Osaxely** [comment]
Je vais voir 👍

**Comment by ThibautTrarbach** [comment]
Ok ;)

**Comment by Osaxely** [comment]
Donc j'obtiens Unknow cas : ac-dijon certainement parce que le fichier n'est plus présent, est-ce que le simple fait de le glisser avec sa dépendance (kdecole-wayf.js) le fera fonctionner ?

**Comment by ThibautTrarbach** [comment]
Je plus simple sa serait de download la branche master et remplacer tout les fichier dans le node module.

Tu sera moins embêter

**Comment by ThibautTrarbach** [comment]
Excuse tromper de button ;)

**Comment by Osaxely** [comment]
la même erreur se produit 😓
Voilà le code :
```
const pronote = require('pronote-api');

// Exemple
const url = 'https://0211033j.index-education.net/pronote/';
const username = 'MonNomUtilisateur';
const password = 'LeMDP';

async function main()
{
    const session = await pronote.login(url, username, password, 'ac-dijon');
    
    console.log(session.user.name); // Affiche le nom de l'élève
    console.log(session.user.studentClass.name); // Affiche la classe de l'élève
    
    const timetable = await session.timetable(); // Récupérer l'emploi du temps d'aujourd'hui
    const marks = await session.marks(); // Récupérer les notes du trimestre
    
    console.log(`L'élève a ${timetable.length} cours aujourd'hui`); 
    console.log(`et a pour l'instant une moyenne de ${marks.averages.student} ce trimestre.`);
    
    // etc. les fonctions utilisables sont 'timetable', 'marks', 'contents', 'evaluations', 'absences',
    // 'infos', et 'menu', sans oublier les champs 'user' et 'params' qui regorgent d'informations.
}

main().catch(err => {
    if (err.code === pronote.errors.WRONG_CREDENTIALS.code) {
        console.error('Mauvais identifiants');    
    } else {
        console.error(err);
    }
});
```
J'ai mis le lien pronote de mon Lycée au cas où ça pourrait aider, et voilà l'erreur précise que ça produit :
```
TypeError: Cannot read property 'value' of undefined
    at login (c:\Users\Osaxely\node_modules\pronote-api\src\cas\generics\kdecole-wayf.js:42:59)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getStart (c:\Users\Osaxely\node_modules\pronote-api\src\auth.js:60:12)
    at async Object.login (c:\Users\Osaxely\node_modules\pronote-api\src\auth.js:15:19)
    at async main (c:\Users\Osaxely\Desktop\Pronote api\pronoteAPI.js:10:21)
```
Merci d'avance :)

**Comment by ThibautTrarbach** [comment]
Hello tu clique sur quel button ici ? :
![image](https://user-images.githubusercontent.com/30575266/94726274-4e928880-035d-11eb-8e6b-bde0a6ce754b.png)

cdt
thibaut

**Comment by Osaxely** [comment]
Quand je me connecte normalement, je clique sur 'Des collèges et des lycées de l'académie de Dijon' (c'est un lycée)

**Comment by ThibautTrarbach** [comment]
Tu peux test avec mon commit que j'ai fait a l'instant ?

Cdt
Thibaut

**Comment by Osaxely** [comment]
Ok je vais voir !

**Comment by Osaxely** [comment]
ça fonctionne ! Merci beaucoup 👍

**Comment by ThibautTrarbach** [comment]
Derien ;)
