### ISSUE TITLE
une documentation pour l'api

### ISSUE THREAD

**Issue by Spokaren** [Litarvan/pronote-api#117]
Bonjour,
J'aimerais savoir si c'est possible de faire une documentation pour l'api (je suis débutant)
Merci d'avance

**Comment by ThibautTrarbach** [comment]
Hello,

Tu a Deja les info d'utilisation dans le readme du repo.

Cdt
Thibaut

**Comment by Litarvan** [comment]
Salut ! Il te suffit de lire le README et de regarder le fichier typings.d.ts :)
