### ISSUE TITLE
rajout cas 

### ISSUE THREAD

**Issue by gibbs4747** [Litarvan/pronote-api#120]
Hello, je souhaite faire un petit programme avec votre projet mais le CAS de mon établissement n'est pas proposé dans votre projet... 
Il serait possible de rajouter le CAS de mon-ent-occitanie.fr ? si c'est possible bien évidemment ! 👍 
je vous remercie !

**Comment by ThibautTrarbach** [comment]
Hello,

Elle est normalement déjà compatible : 

![image](https://user-images.githubusercontent.com/30575266/95022628-bc4df580-0678-11eb-8bc6-2ad05760590c.png)

Cdt
Thibaut

**Comment by gibbs4747** [comment]
hmm, c'est bizarre, lorsque je lance mon script, on me fournit comme erreur "mauvais identifiants".. y a un truc qui cloche non ? :/

cdt

**Comment by Androz2091** [comment]
Tu utilises `ac-toulouse` ou `ac-montpellier`? Tu peux envoyer le lien de ton serveur pronote et ton code ?
Je peux regarder plus en détails sur Discord si tu veux `Androz#2091`

**Comment by gibbs4747** [comment]
je viens de t'ajouter ! :)

**Comment by ThibautTrarbach** [comment]
Résolut en privée sur discord avec @Androz2091
