### ISSUE TITLE
TypeError: Cannot read property 'urlSiteIndexEducation' of undefined

### ISSUE THREAD

**Issue by gibbs4747** [Litarvan/pronote-api#121]
Hello, quand je lance mon projet, avec des codes correctes et validé par ANDROZ (ça marche chez lui mais pas chez moi), une erreur apparait : 
TypeError: Cannot read property 'urlSiteIndexEducation' of undefined
    at getParams (C:\Users\....\node_modules\pronote-api\src\fetch\pronote\params.js:28:46)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.login (C:\Users\....\node_modules\pronote-api\src\auth.js:31:22)
    at async main (C:\Users\....\PhpstormProjects\untitled\gghometest.js:10:21)

alors que quand j'exécute le projet de démonstration de pronote, ça marche très bien ! 
si quelqu'un à la solution... merci !

cdt

**Comment by ThibautTrarbach** [comment]
Hello,

Tu utilise quel version de l'api ?
@Androz2091 Pareil de ton cotée tu utilise quel version ?

Cdt
Thibaut

**Comment by gibbs4747** [comment]
> Hello,
> 
> Tu utilise quel version de l'api ?
> @Androz2091 Pareil de ton cotée tu utilise quel version ?
> 
> Cdt
> Thibaut

hello, moi j'utilise la dernière à savoir la 2.1.3

**Comment by ThibautTrarbach** [comment]
Ok, 

Et je parie de @Androz2091 utilise la beta en direct de la branche master ou account ?

Cdt
Thibaut

**Comment by gibbs4747** [comment]
> Ok,
> 
> Et je parie de @Androz2091 utilise la beta en direct de la branche master ou account ?
> 
> Cdt
> Thibaut

aucune idée !

**Comment by ThibautTrarbach** [comment]
Soit on attend que @Androz2091 réponde,
Soit tu télécharge la branche master et tu test avec celle ci.

Cdt
Thibaut

**Comment by gibbs4747** [comment]
> Soit on attend que @Androz2091 réponde,
> Soit tu télécharge la branche master et tu test avec celle ci.
> 
> Cdt
> Thibaut

tu peux me rappeler la commande pour installer la branche master ? merci ! 

cdt

**Comment by ThibautTrarbach** [comment]
Hello,

Sa depend de ton os,
Mais le plugin simple est de télécharger le zip sur la page principale;

Cdt
Thibaut

**Comment by gibbs4747** [comment]
> Hello,
> 
> Sa depend de ton os,
> Mais le plugin simple est de télécharger le zip sur la page principale;
> 
> Cdt
> Thibaut

bingo, ça marche !

**Comment by ThibautTrarbach** [comment]
Voila,

Il y a eux beaucoup de debug et d'ajout de fonction par rapport a celle sur NPM.

Ps : Je peux close tes 2 demande ?

Cdt
Thibaut

**Comment by gibbs4747** [comment]
> Voila,
> 
> Il y a eux beaucoup de debug et d'ajout de fonction par rapport a celle sur NPM.
> 
> Ps : Je peux close tes 2 demande ?
> 
> Cdt
> Thibaut

oui c'est good ! merci beaucoup

cdt
