### ISSUE TITLE
period en trimestre ??

### ISSUE THREAD

**Issue by bugsounet** [Litarvan/pronote-api#123]
@ThibautTrarbach je comprend pas pourquoi tu utilise encore period en trimestre

sur periods.js , peut-etre plutot :         
```
return periods.find(p => now >= p.from && now <= p.to && p.kind === 'semester') || periods[5];
```
car en trimestre cela ne sort aucun resultat (avec compte parent) sauf si on force "Semestre 1" mais bon c'est mieux en auto :)

(peut-etre revoir absences.js également dans ce cas)

**Comment by ThibautTrarbach** [comment]
Hello,

Pareil, sa sa dépend des établissements.
Moi dans mes 3 établissements de test, 
J'en ai 2 en trimestre et 1 en semestre.

Et les plus commun sont les trimestre. Donc on met les trimestre de base.

Cdt
Thibaut

**Comment by bugsounet** [comment]
dans ce cas pourquoi ne pas ajouter un string `type`

`function getPeriodBy(session, period, type)`

`type` serait `trimestre` ou `semestre` ?

**Comment by Litarvan** [comment]
Le but de `getPeriodBy` est de renvoyer un objet de période en fonction de ce qui est demandé, notamment le nom d'une période (exemple : `Trimestre 1`, `Semestre 1`), ou si rien n'est renseigné, de renvoyer le trimestre actuel (car c'est ce qui est le plus couramment utilisé). J'ai du mal à comprendre le problème de base, effectivement dans certains cas les trimestres ne sont pas utiles, mais il suffit alors de demander une autre période.

**Comment by bugsounet** [comment]
sauf que ... dans mon côté c'est l'inverse, 80% de mes users sont en semestres.
et le but et de recuperer les infos selon le trimestre ou le semestre en automatique selon les date defini du trimestre ou semestre en cours

donc c'est pour cela que le string `type` permetrai de choisir (selon l'établissement soit en trimestre, soit en semestre)

type defini sur trimestre retourne l'object du trimestre courant (si type defini):

```
[2020-10-05 16:21:13.546] [LOG]    type: trimester
[2020-10-05 16:21:13.547] [LOG]    Period: {
  id: '111B79A8C515799',
  name: 'Trimestre 1',
  kind: 'trimester',
  notationPeriod: 0,
  from: 2020-08-31T22:00:00.000Z,
  to: 2020-11-22T23:00:00.000Z
}
```

avec type = semester

```
[2020-10-05 16:19:33.581] [LOG]    type: semester
[2020-10-05 16:19:33.581] [LOG]    Period: {
  id: '1116431B0E47895',
  name: 'Semestre 1',
  kind: 'semester',
  notationPeriod: 3,
  from: 2020-08-31T22:00:00.000Z,
  to: 2021-01-17T23:00:00.000Z
}
```

**Comment by Litarvan** [comment]
:thinking: Ca ferait un paramètre supplémentaire pour toutes les requêtes qui utilisent getPeriodBy de base, mais je vais voir comment on pourrait faire ça facilement, c'est vrai que c'est une bonne idée

**Comment by bugsounet** [comment]
Je l'ai deja codé au cas ou ...
