### ISSUE TITLE
Intégration du CAS d'Auvergne Rhone Alpes ?

### ISSUE THREAD

**Issue by korobaka** [Litarvan/pronote-api#125]
Salut,
Je trouve ton concept ultra intéressant et j'aimerai bien l'utiliser pour ma classe !
Cependant, je suis en Auvergne Rhone Alpes et je n'ai donc aucun moyen d'utiliser ton api... à quand une intégration pour le CAS de l'ENT d'ARA ?

**Comment by ThibautTrarbach** [comment]
Hello,

Possible d'avoir un lien de l'ent ?

Cdt
Thibaut

**Comment by korobaka** [comment]
Yoo,
c'est ici : https://ent.auvergnerhonealpes.fr

**Comment by ThibautTrarbach** [comment]
Hello,

J'ai une bonne nouvelle, elle est déjà compatible.

Cdt
Thibaut

**Comment by korobaka** [comment]
Niiice ! J'installe le package quand j'ai fini les cours !
Merci !
