### ISSUE TITLE
A lot of unhandled promises

### ISSUE THREAD

**Issue by busybox11** [Litarvan/pronote-api#128]
I often get unhandled promises rejections. This is not caused by my program but by the API itself (see screenshot below).
![image](https://user-images.githubusercontent.com/29630035/95323354-517e0380-089e-11eb-9b13-a45eb09f8be0.png)

A comprehensive custom error with details about the error (if possible) could be returned, instead of this promise error.

**Comment by Androz2091** [comment]
Je pense que cela peut-être dû au fait que tu effectues plusieurs requêtes simultanément (sans attendre avec `await` ou `.then`). Est ce que tu peux essayer de voir si tu aurais un cas comme celui là dans ton code ?

**Comment by busybox11** [comment]
Ca me le fait même avec les await (mon code est asynchrone).
Par contre j'ai potentiellement une piste, ca serait le client qui expire...
![image](https://user-images.githubusercontent.com/29630035/95364387-0df0bd00-08d1-11eb-9f75-bf19d9ef9302.png)

**Comment by busybox11** [comment]
Toujours pareil un jour après, je n'ai rien changé, le serveur de test et mon lycée font pareil.

![image](https://user-images.githubusercontent.com/29630035/95508263-fe49a500-09b2-11eb-87e0-1e841dd96f4e.png)
 (c.f. https://github.com/Litarvan/pronote-api/issues/106#issuecomment-705796244)

**Comment by bugsounet** [comment]
j'ai le meme souci, j'ai l'impression qu'il ne garde pas la session ouverte et fait ne fait pas correctement le relogin automatique au cas ou ... [session.setKeepAlive(true)]
j'ai pas encore regarder le pourquoi du comment.. (pas encore eu le temps).
cela arrive generalement au bout de +/- 24h

pour le moment de mon coté pour contrer le problème:
 * session.setKeepAlive(false)
 * je fais un login, fetch et termine par un logout une fois toutes les infos recupérés

**Comment by bugsounet** [comment]
ah bon... pourquoi `wontfix` ?
ben je vais quand même regarder de mon côté

**Comment by ThibautTrarbach** [comment]
Car c'est une erreur de ma part.
Mais sinon pour en revenir a l'erreur,
Je confirme que l'on pas la faire durée indéfiniment. 
Pronote kill les session de plus de temps de temps.

Par contre je suis dans l'incapcacité de vous dire au bout ce combien de temps.
Une autre info, si vous faite un requête non valide,
cela faire la session.
Ou alors si une limite de nombre de client est atteint sur le compte.
Pareil je sait pas combien, mais je sait que sa se passe.

Cdt
Thibaut

**Comment by bugsounet** [comment]
en fait, j'ai vu le probleme :)

il se situe dans `src/session.js`

dans la fonction setKeepAlive(), tu verifies si il y a une erreur en envoyant une request `presence`
jusque la pas de souci ;)

j'ai donc verifier la valeur de `onError` : elle n'est pas définie
de plus si la requete `presence` retourne une erreur ben ... cela ne fait tombé isKeptAlive sur `false`

* donc j'imagine 2 scénarios:
1) la session a été cloturé... donc pas de relogin -> isKeptAlive va sur `false`
2) coupure temporaire d'internet (chgt d'ip forcer par le provider par exemple) retourne une erreur -> IsKeptAlive va sur `false` aussi

il faudrait eventuellement replacer un login automatique en cas d'erreur

```
[2020-10-12 18:34:37.234] [LOG]    [PRONOTE] Pronote Login.
[2020-10-12 18:34:43.225] [LOG]    [API] true false undefined 60 <-- value of : enabled, this.isKeptAlive, onError, rate
[2020-10-12 18:34:43.226] [LOG]    [API] waiting... interval
[2020-10-12 18:34:43.226] [LOG]    [API] keepAlive set to true
[2020-10-12 18:34:43.227] [LOG]    [PRONOTE] Pronote fetch data.
[2020-10-12 18:34:44.771] [LOG]    [PRONOTE] Pronote is initialized.
[2020-10-12 18:35:43.226] [LOG]    [API] interval <-- execute interval
[2020-10-12 18:35:43.227] [LOG]    [API] err! <-- I force err in keepAlive()
[2020-10-12 18:35:43.227] [LOG]    [API] false true undefined 60 <-- value of : enabled, this.isKeptAlive, onError, rate
[2020-10-12 18:35:43.228] [LOG]    [API] ClearInterval
[2020-10-12 18:35:43.228] [LOG]    [API] keepAlive set to false
[2020-10-12 18:35:44.751] [LOG]    [PRONOTE] Pronote fetch data.
[2020-10-12 18:35:46.340] [LOG]    [PRONOTE] Pronote data updated.
```

**Comment by Litarvan** [comment]
Le login automatique revient à enregistrer les informations, on préfère laisser la liberté de le faire à l'utilisateur de la lib plutôt que d'intégrer ça. Anyway je vais essayer de gérer la Promise correctement.

**Comment by bugsounet** [comment]
ah... c'est con j'avais presque fini de le coder.
j'avais mis la config dans la session pour la rappeler au login lol

**Comment by busybox11** [comment]
Donc comment il faudra faire ? On va devoir faire nous même la déconnexion c'est ça ?

**Comment by bugsounet** [comment]
> pour le moment de mon coté pour contrer le problème:
> * session.setKeepAlive(false)
> * je fais un login, fetch et termine par un logout une fois toutes les infos recupérés

**Comment by Litarvan** [comment]
@busybox11 Si Pronote refuse absolument de laisser la session ouverte trop longtemps, soit tu setKeepAlive(true) et lors d'une erreur tu l'arrêtes, tu logout, et tu relogin, soit dès que t'as besoin de pronote tu ouvres une session (sans setKeepAlive) et tu la fermes après.

**Comment by Litarvan** [comment]
Au passage, ce problème est-il présent sur master ? Parce que je viens de réaliser, mais je gère bien la Promise (je me rappelle en revanche que ce n'était pas le cas avant).

**Comment by bugsounet** [comment]
moi perso j'avais le cas sur le multi mais je crois que tu as fusionner avec le master maintenant non ?

**Comment by Litarvan** [comment]
Je ferme car on n'a pas réussi à reproduire
