### ISSUE TITLE
Ajouter le cas ent.parisclassenumerique.fr

### ISSUE THREAD

**Issue by Androz2091** [Litarvan/pronote-api#135]
Ce cas est manquant : 

URL Pronote : https://0753939z.index-education.net/pronote/
URL du cas : https://ent.parisclassenumerique.fr/auth/login?callback=%2Fcas%2Flogin%3Fservice%3Dhttps%253A%252F%252F0753939Z.index-education.net%252Fpronote%252F

**Comment by Androz2091** [comment]
My bad je viens de le trouver 😅

**Comment by ThibautTrarbach** [comment]
Hello,
Yes, je l'ai rajouter hier a la demande de 1 de mes user.

Cdt
Thibaut
