### ISSUE TITLE
Banned IP

### ISSUE THREAD

**Issue by JuanPampa** [Litarvan/pronote-api#138]
Hi there,

I've been working with your pronote-api repository and while doing some requests, I've been banned several times from doing any of those for a certain amount of time.

I just wondered if there was something to do to get whitelisted somewhere, so that my website ip address doesn't get banned..

Regards,
Juan

**Comment by Litarvan** [comment]
Hey ! There isn't anything you can do except reducing the amount of requests you are doing :/
