### ISSUE TITLE
Informations concernant la ratelimit

### ISSUE THREAD

**Issue by Androz2091** [Litarvan/pronote-api#139]
Bonjour,
Je développe actuellement une application mobile qui interagit avec l'API de Pronote, mais de temps en temps (après trop de mots de passe invalides essayés par les utilisateurs) l'IP de mon serveur est temporairement bannie. J'imagine que l'on ne peut pas grand chose contre ça, mais j'aimerai savoir si vous auriez plus d'informations ? (nombre de tentatives avant que l'IP soit bannie, est-ce que cette ratelimit est globale ou seulement par serveur Pronote, etc.) 
Merci 👍

**Comment by ThibautTrarbach** [comment]
Hello,

J'ai une bonne et mauvaise nouvelle pour toi,
La bonne est que je sait comment sa fonctionne.

La mauvaise est que c'est au choix de l'etablisement (Serveur Pronote de test Personnel) : 
Pour les ip non privilégiées : 
Sécurité Désactivé : 
![image](https://user-images.githubusercontent.com/30575266/97078577-5a383e80-15ed-11eb-9918-4e4542cf74ed.png)
Sécurité Faible : 
![image](https://user-images.githubusercontent.com/30575266/97078581-615f4c80-15ed-11eb-9bc4-8b911bb46a77.png)
Sécurité Moyen : 
![image](https://user-images.githubusercontent.com/30575266/97078538-2826dc80-15ed-11eb-93ab-aa349764881c.png)
Sécurité élevé : 
![image](https://user-images.githubusercontent.com/30575266/97078591-6de3a500-15ed-11eb-96c7-99b0263563e9.png)

Second system de securité en plus du premier : 
![image](https://user-images.githubusercontent.com/30575266/97078617-99ff2600-15ed-11eb-8088-a977057d6e5e.png)

Et pour te donner une idée de toute les securité que tu doit passer : 
![image](https://user-images.githubusercontent.com/30575266/97078693-16920480-15ee-11eb-995b-7789637d6160.png)

**Comment by ThibautTrarbach** [comment]
Et si tu veux plus d'info envoit moi un message sur discord. Je t'ai déjà en ami.

cdt
Thibaut

**Comment by Androz2091** [comment]
Merci pour toutes ces infos, c'est exactement ce qui m'intéressait ! 😄 
Si j'ai bien compris, le blocage de l'IP se fait donc localement sur chaque serveur Pronote, ce qui veut dire que si un serveur Pronote bloque temporairement mon serveur, ce ne sera pas le cas pour tous ?
Et on a donc aucun moyen de savoir quel est le type de sécurité sur chaque serveur... Est-ce que tu sais quel est le paramètre par défaut ?

> Et si tu veux plus d'info envoit moi un message sur discord. Je t'ai déjà en ami.

Je pense que cette issue pourra être utile à tout le monde mais je veux bien ton pseudo Discord oui si possible 😃 
Merci

**Comment by ThibautTrarbach** [comment]
Mon pseudo est Thibaut Black sur discord.

Sinon pour répondre a tes question, 

> le blocage de l'IP se fait donc localement sur chaque serveur Pronote

Oui si ton serveur il est ban que du serveur qui ta blacklist.

> Et il n'y a donc aucune rate-limit pour les connexions si celles-ci réussissent ? 
Je suis pas sur, mais je pense que si, si tu regarde sur mes premier screen, tu a une saturation UDP par seconde indiqué, je pense que sa a voir avec sa. (Mais toujours par serveurs)

>  En théorie je peux me connecter sans problème avec un nombre de comptes illimité, à un intervalle de temps plus ou moins rapproché, sans que ça pose de problème si les mots de passes sont corrects ? 

En théorie, si tu gère le rate limite et les erreur du a des mots de passe erroné, alors oui je pense que cela est possible.

> Est-ce que tu sais quel est le paramètre par défaut 

Moi j'ai jamais toucher au config du serveur et je suis partout en moyen, donc je pense que c'est la configuration de base.

Cdt
Thibaut
