### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Vorlod-exe** [Litarvan/pronote-api#150]
Bonjour et merci pour ce travail, je n'ai malheureusement pas trouvé la documentation de cet API. 
Existe-t-elle et si oui, où la trouver ? 
Merci d'avance 😃

**Comment by ThibautTrarbach** [comment]
Oui pour l'instant c'est le readme dans la branche master.

cdt
Thibaut

**Comment by Vorlod-exe** [comment]
N'y a-t-il pas une liste des propriétés ?

**Comment by Vorlod-exe** [comment]
Ok merci
