### ISSUE TITLE
Cas Oise - Soucis d'authentification "Invalid credential"

### ISSUE THREAD

**Issue by Raphelvo** [Litarvan/pronote-api#155]
Bonjour, pour l'oise j'ai le lien suivant :  
https://teleservices.ac-amiens.fr/sso/SSO?SPEntityID=urn:fi:ent:amiens-hdf-ts:1.0&TARGET=https://enthdf.fr/

J'ai essayé de patcher le cas limoge mais sans succès. "Invalid crédential"
J'ai tenté le lien direct sans succès non plus.

Comment avancer sur le problème ?

**Comment by ThibautTrarbach** [comment]
Hello,
Pourquoi avoir voulu passer par le lien de limoge alors que vous êtes dans l'oise ?

Cdt
Thibaut

**Comment by Raphelvo** [comment]
Parce que il n'y a pas de cas Oise, que le cas "hdf" ne fonctionne pas. Le lien de connexion n'est pas https://enthdf.fr/ mais celui donné plus haut. Si je me connexte avec enthdf il me dit "invalid credential". 

Cela semble bon pour la Somme (lien de connexion = https://enthdf.fr/auth/login) mais pas pour l'Aisne, le Nord ou l'oise qui utilise a prioris le meme SSO que limoges avec un compte "ATEN" (avec des adresse http differentes)

**Comment by ThibautTrarbach** [comment]
Hello,

Tu peux me donné, la façon d'allé sur aten (Lien Pronote, Lien premiere ENT, Lien du aten)

Cdt
Thibaut

**Comment by Raphelvo** [comment]
D'accord. Il est possible que j'ai pas fait les bonnes manips.

Choix de l'ENT : https://connexion.enthdf.fr
Lien de connexion : https://teleservices.ac-amiens.fr/login/ct_logon_vk.jsp?CT_ORIG_URL=%2Fsso%2FSSO%3FSPEntityID%3Durn%3Afi%3Aent%3Aamiens-hdf-ts%3A1.0%26TARGET%3Dhttps%3A%2F%2Fenthdf.fr%2F&ct_orig_uri=%2Fsso%2FSSO%3FSPEntityID%3Durn%3Afi%3Aent%3Aamiens-hdf-ts%3A1.0%26TARGET%3Dhttps%3A%2F%2Fenthdf.fr%2F
Le paramètre CT_ORIG_URL semble obligatoire sinon le login ne passe pas.
Le parametre ct_orig_uri n'a  a prioris pas d'impact (avec CT_ORI_URL renseigné)
URL Pronote : https://0601766u.index-education.net/pronote/ (c'est bien cette url qu'on met dans le parametre url de l'api ?)

**Comment by bugsounet** [comment]
de mon côté, je suis en hdf aussi (nord). j'ai le meme probleme. J'ai résolu en utilisant les identifiants [ENT]( https://enthdf.fr/auth/login)

le schéma de connexion pour devrai HDF est ainsi : auth teleservice -> auth ENT -> auth pronote
mais le callback de pronote donne ceci: auth ENT -> auth Pronote

les identifiant de 'teleservices' ne fonctionne pas. il faut utiliser les identifiants [ENT]( https://enthdf.fr/auth/login)

si vous arrivez a vous connecter cela devrai fonctionner avec l'api (fonctionne dans mon cas actuellement)


ps: avantage sur un ordi ... 90% du temps teleservice est HS mais pas l'ENT et c'est plus rapide :)

**Comment by bugsounet** [comment]
confirmation que cela fonctionne avec cette astuce : [ici](https://github.com/delphiki/MMM-Pronote/issues/27#event-3997494318)

**Comment by Raphelvo** [comment]
Merci pour l'information... sauf que je n'ai qu'un identifiant, a prioris téléservice.

**Comment by bugsounet** [comment]
dans ce cas, rien de plus simple :)

essaye ceci :  
connecte toi dans l'ENT, va dans `mon compte` (avant derniere icone en haut a droite)
tu veras donc ton `Identifiant`
ensuite a toi de faire `mot de passe oublier` via [ENT](https://enthdf.fr/auth/login)

**Comment by Raphelvo** [comment]
Ok ca a l'air d'aller plus loin avec mon compte parent. Je verrais demain avec mon fils pour pas lui couper l'accès, je peux pas lui remettre le meme mot de passe que TeleService.
La manip ne casse pas le lien ENT / Teleservice / pronote ? Maintenant quand je me connecte avec teleservice maintenant il me dit que j'ai plus le droit d'utiliser ce service... par contre quand j'utilise ENT ca fonctionne. Pas trop envie de casser qque chose chez lui :(

**Comment by Raphelvo** [comment]
Rajout, je viens de tester ok  en  tant que parent (le paramètre est case sensitive),. Merci beaucoup. Je vais voir ce que je peux faire avec mon compte.
pronote-fetch https://0601766u.index-education.net/pronote/ monlogin monpass hdf parent

en résumé sur mon erreur j'utilisais le seul login que j'avais, celui de teleservice alors qu"il faut demander celui de l'ENT.
