### ISSUE TITLE
Problèmes ENT normandie

### ISSUE THREAD

**Issue by Sotoamino** [Litarvan/pronote-api#156]
Bonjour, l'API ne fonctionne pas avec l'ENT Arsene76 
![image](https://user-images.githubusercontent.com/59519426/98453601-4d722980-215b-11eb-8208-dc25549902fb.png)

De même, serait-il possible d'ajouter l'ENT nero.l-educ-de-normandie ?
https://nero.l-educdenormandie.fr

**Comment by Sotoamino** [comment]
//edit : l'ENT Nero Normandie fonctionne

**Comment by ThibautTrarbach** [comment]
Hello,

Alors pour :  Arsene "Académie de Rouen", Je peux déjà te dire que sa fonctionne sans problème, J'ai 5 utilisateur dessus, et je viens de test avec 3 de leur compte.

Ensuite pour le cas  l'ENT nero.l-educ-de-normandie, cela existe déjà sous le nom de ac-rouen 

Cdt
Thibaut
