### ISSUE TITLE
Ajouter un cas

### ISSUE THREAD

**Issue by lyanissouidi** [Litarvan/pronote-api#158]
Bonjour,
Pouvez-vous ajouter le cas de la région Centre-Val de Loire **pour les lycées** svp ?
Lien de l’ent : [https://netocentre.fr/](https://netocentre.fr/)  

Merci

**Comment by ThibautTrarbach** [comment]
Hello,

Le cas existe déjà sous le nom de "ac-orleans-tours" : 
![image](https://user-images.githubusercontent.com/30575266/98464795-7202eb80-21c5-11eb-9bf5-affe90c96552.png)

Cordialement
Thibaut

**Comment by lyanissouidi** [comment]
Merci je ne l’avais pas vu 😅
