### ISSUE TITLE
SyntaxError: Unexpected token y in JSON at position 1

### ISSUE THREAD

**Issue by Cyborger** [Litarvan/pronote-api#16]
Error when trying to use the API :
`SyntaxError: Unexpected token y in JSON at position 1                                                                       at JSON.parse (<anonymous>)                                                                                             at IncomingMessage.<anonymous> (C:\Users\cyb0r\OneDrive\Projets personnel\seconde-5-bot\pronote-api\index.js:28:31)     at IncomingMessage.emit (events.js:215:7)                                                                               at endReadableNT (_stream_readable.js:1184:12)                                                                          at processTicksAndRejections (internal/process/task_queues.js:80:21)`

Using the POST method with this content : 
```json
{
            "type": "fetch",
            "username": pronote[0],
            "password": pronote[1],
            "url": "https://HIDDEN.index-education.net/pronote/",
            "cas": "none"
}

**Comment by wow0000** [comment]
Hey, if  could you send the full POST request that you're making to the server ? (Like the code, functions, that you could use).
If you want to check what the server receive, add `console.log(body)` line 28 just before `let params = JSON.parse(body);`. This may help you finding where does the bug come from

**Comment by Cyborger** [comment]
Thank you for the help, I just found out what was wrong, my script is in Python
```python
import requests

payload = {
    "type": "fetch",
    "username": "me",
    "password": "pass",
    "url": "https://hidden.index-education.net/pronote/",
    "cas": "none"
}

r = requests.post("http://127.0.0.1:21727/", data=payload)
print(r.text)
```
I used `data=payload` as a parameter and it needed the JSON parameter
