### ISSUE TITLE
Node.js >= 11.14.0 vs Alexa

### ISSUE THREAD

**Issue by madsenfr** [Litarvan/pronote-api#160]
Bonjour,

Je souhaite réaliser une application pour l'assistant vocal d'Amazon, mais malheureusement l'ajout de pronote-api provoque une erreur au build.

Il semble que cela soit dû à cette définition du package.json, car la version de Node.js imposée par la plateforme Alexa, est v10.22.1 :
```
    "engines": {
        "node": ">=11.14.0"
    }
```
Est-ce qu'il y a une alternative ?
pronote-api ne peut-elle réellement pas fonctionner en dessous de la version 11.14.0 ?

**Comment by Litarvan** [comment]
On a pas testé mais ça devrait fonctionner, tu peux manuellement changer ça dans le package.json

**Comment by ThibautTrarbach** [comment]
@madsenfr Des nouvelle ?

**Comment by madsenfr** [comment]
Je cherche comment mettre ma propre dependencies dans le package.json Alexa, car actuellement elle est récupérée directement sur npm, donc avec l'exigence node >=11.14.0.

**Comment by ThibautTrarbach** [comment]
ok, tu peux pas faire des test en local et nous dire ? 
Car si sa passe on peux peux etre baisser le niveaux sur l'api

Cdt
Thibaut

**Comment by madsenfr** [comment]
J'utilise la console de dev online, du coup je n'ai pas la possibilité de tester en local.
Mais je cherche comment faire...

**Comment by madsenfr** [comment]
J'ai forké votre repo, pour seulement modifier la version minimale requise de node et maintenant ça build et ça fonctionne avec l'exemple de code que vous fournissez.

Par contre, j'ai l'erreur "Mauvais identifiants" (que j'ai vérifiés).
Pour info, je suis un parent d'élève, j'ai l'application mobile Pronote, mais pas accès au site Pronote en direct, je dois passer par toutatice.fr (académie de Rennes).
Donc, je mets mes identifiants educonnect pour le site toutatice.fr de l'académie de Rennes, en ajoutant le dernier paramètre "cas" = "toutatice" dans l'appel à pronote.login.
J'ai vérifié l'url de mon site pronote.
Ai-je loupé quelque chose ?

**Comment by ThibautTrarbach** [comment]
Oui tu a louper sa : 

https://github.com/Litarvan/pronote-api/issues/21

Cdt
Thibaut

**Comment by madsenfr** [comment]
Oui, en plus j'étais déjà tombé dessus en cherchant la bonne API pronote.
Je regarde si je peux obtenir un compte Pronote en direct, sans passer par le site de l'académie...

**Comment by ThibautTrarbach** [comment]
@Litarvan A normalement toute les information, mais de souvenir il est en periode d'examen .

Cdt
Thibaut

**Comment by ThibautTrarbach** [comment]
Hello,

J'ai une bonne et mauvaise nouvelle.

La bonne est que j'ai une réponse pour toi.
La mauvaise est que non l'api ne peux pas tourné en dessous de la version 11 : 
![image](https://user-images.githubusercontent.com/30575266/99879171-4a6f4280-2c0b-11eb-95c0-432df34a99d2.png)

Cdt
Thibaut

**Comment by madsenfr** [comment]
C'est bizarre, car je l'ai fait tourné sous Node v10.22.1 et je n'ai pas eu d'erreur.
J'ai fait utilisé l'exemple et j'ai obtenu les valeurs sans erreur.
Par contre, ensuite c'est l'accès à toutatice (AC Rennes) qui pose problème et me retourne un problème d'authentification, là encore sans erreur.

**Comment by ThibautTrarbach** [comment]
Toutatice c'est normal, elle vient d'etre debug today.

Et pour l'erreur je te la confirme, c'est celle de la master actuel

**Comment by Androz2091** [comment]
A la limite on peut s'arranger pour ne plus avoir besoin du `fs.promises` si ce n'est que ça qui pose problème (il y a seulement quelques lignes à modifier)

**Comment by madsenfr** [comment]
La version Node sur Amazon Alexa vient de passer à 10.23.0.
Lorsque j'utilise madsenfr/pronote-api je n'ai pas d'erreur, peut-être parce qu'il est indiqué "backported 10.17.0" dans le screenshot de @ThibautTrarbach.

Je viens de mettre à jour mon fork madsenfr/pronote-api sur celui de Litarvan (branche master).
Mon problème reste celui du message "Mauvais identifiants", malgré la correction.
Je suis nouveau sur Github, pouvez-vous confirmer que issues/21 est bien corrigé par pull/172 et que tout cela est sur la branche master, SVP ? Et que j'ai bien synchronisé mon fork madsenfr/pronote-api ?
J'ai un doute car pull/171 semble HS, mais je ne suis pas sûr de ce que cela signifie.

**Comment by ThibautTrarbach** [comment]
La raison est simple, nous avons pas encore merge la pull request, @Litarvan va faire un petit tours dessus avant.

Cdt
Thibaut

**Comment by madsenfr** [comment]
Merci pour l'info.
Je vais surveiller la pull request et je vous tiendrais au courant si j'arrive à me connecter.

**Comment by JBX028** [comment]
Bonjour,
Je m'infiltre dans la conversation. Je suis en train de créer une application pour google home en utilisant actions on google et dialogflow avec un focus sur les devoirs et les notes. Le problème c'est comment gérer la connection sans "hardcoder" l'url, l'id le mot de passe et le cas. Je serais intéressé d'échanger @madsenfr à ce sujet car j'imagine que tu dois avoir le même problème avec Alexa.

**Comment by madsenfr** [comment]
Discussion en MP

**Comment by Raphelvo** [comment]
Vous m'inquietez, je suis en v10.21.0.

**Comment by madsenfr** [comment]
> Vous m'inquietez, je suis en v10.21.0.

Il faut changer la version node dans package.json:
`"engines": {
        "node": ">=11.14.0"
    },`

J'ai fait un fork sur https://github.com/madsenfr/pronote-api avec une version antérieure et ça semble fonctionner.
J'étais à 10.23.0, je viens de passer à 10.21.0, si tu veux tester.

**Comment by madsenfr** [comment]
> Hello,
> 
> J'ai une bonne et mauvaise nouvelle.
> 
> La bonne est que j'ai une réponse pour toi.
> La mauvaise est que non l'api ne peux pas tourné en dessous de la version 11 :
> ![image](https://user-images.githubusercontent.com/30575266/99879171-4a6f4280-2c0b-11eb-95c0-432df34a99d2.png)
> 
> Cdt
> Thibaut

@ThibautTrarbach 
Suite au test effectué avec l'aide de 3l0w, c'est bien ma version node 10.23.0 qui pose problème.
Le code commun lorsqu'on passe par une identification directe via pronote semble fonctionner, mais pas en utilisant l'identification via un CAS.
Pour rappel je ne peux pas upgrader NodeJs, car j'utilise un env Amazon Alexa dans le cloud sur lequel je n'ai pas la main.
Les logs fournies par Amazon ne me donnent pas d'erreur, à part l'exception lorsque j'utilise pronote.login avec le dernier paramètre CAS.

**Comment by madsenfr** [comment]
> A la limite on peut s'arranger pour ne plus avoir besoin du `fs.promises` si ce n'est que ça qui pose problème (il y a seulement quelques lignes à modifier)

@Androz2091 
Suite à mon message précédent, si c'est faisable ça m'intéresse, car Amazon m'a répondu qu'il ne peuvent pas s'engager sur une roadmap pour l'upgrade de la version NodeJs, ce qui serait l'idéal.
Par contre, afin de ne pas te faire perdre du temps pour rien, il faudrait s'assurer qu'il n'y aura pas d'autres erreurs une fois celle-ci résolue.
En tout cas je suis à ta dispo si je peux aider...
Et maintenant j'ai un discord Ragnar56#8172 ;-)

**Comment by Androz2091** [comment]
@madsenfr j'ai ouvert une PR, tu peux l'utiliser en la clonant depuis mon repo pour la tester et en attendant qu'elle soit merge (ce qui ne sera pas forcément le cas, c'est aux mainteneurs de la lib de voir si ça vaut le coup ou non de supporter la v10 en perdant quelques fonctionnalités)

**Comment by madsenfr** [comment]
@Androz2091 Merci, mais ça ne résout pas le problème, j'obtiens toujours "Mauvais identifiant".
Il doit y avoir d'autres erreurs, mais je n'ai rien dans la log...

**Comment by Androz2091** [comment]
Tu as peut-être des erreurs dans ton code ou des erreurs dues à un environnement incompatible mais le fait est que mon fork **est** compatible avec Node.js v10. C'est sûr (tu peux re-vérifier avec eslint)

**Comment by madsenfr** [comment]
Le code c'est celui de l'exemple, qui fonctionne avec les id de démo, je viens de revérifier suite à ton fork.
Mais ensuite avec mes id et mon url dans les mêmes variables ça passe plus (j'ai vérifié en faisant un copier coller de l'url et de mes id depuis mon code vers un navigateur et ça me connecte bien à pronote).
La différence c'est que je passe le dernier param à pronote.login "toutatice".
Je crois que je vais monter un serveur Node à la bonne version, avec juste l'appel à pronote-api, pour en faire un web service, au moins j'aurais la main sur le backend.
Au passage si vous connaissez des hébergeurs gratuits avec NodeJs ?

**Comment by Androz2091** [comment]
Pour du Node.js, tu peux utiliser `Heroku` (un peu moyen si ton appli commence à prendre un peu d'ampleur), `Glitch` (bien mais un peu lent) ou `Vercel` (j'ai jamais essayé mais ça a l'air vraiment pas mal)

**Comment by madsenfr** [comment]
Bon alors, le problème de mauvais identifiants venait du fait que j'utilisais le code de l'exemple:

`const session = await pronote.login(url, username, password, cas)`

alors qu'il fallait utiliser "loginParent":

`const session = await pronote.loginParent(url, username, password, cas)`

Par contre, maintenant j'ai un autre problème, car la récupération de la session est très longue et j'ai un timeout à 8 s avec l'assistant vocal d'Amazon.
Je vais donc peut-être devoir héberger ailleurs l'appel à pronote-api, afin d'avoir un backend qui se met à jour régulièrement et qui me donne sa dernière session plus rapidement.
À suivre...

**Comment by Androz2091** [comment]
Oui, c'est sans doute la meilleure solution parce qu'en fonction du cas ça peut mettre du temps. Après 8 secondes c'est beaucoup quand même...

**Comment by JBX028** [comment]
C’est en effet la meilleure solution. Je vais voir comment et ou stocker le
json. Un batch job tournant toute les heures devrait suffire je pense.

**Comment by madsenfr** [comment]
J'ai fais des tests sur Glitch (merci @Androz2091).

- Quand je me connecte avec `pronote.loginParent` cela prend +20 s et les données de mon enfant ne sont pas accessibles, ce qui m'a surpris car j'y accède en me connectant manuellement.

- Quand je me connecte avec `pronote.login` et le compte de mon enfant cela prend +15 s et j'ai bien ses données.
La durée est peut-être due au fait que je passe par le CAS toutatice qui utilise educonnect et cela rajoute des étapes, car l'exemple du readme en connexion directe sur Pronote est lui très rapide.

- Autre infos sur la version node:
Sur Glitch j'ai utilisé Node v10.15.3 et cela fonctionne avec juste un warning `(node:6692) ExperimentalWarning: The fs.promises API is experimental`, donc inutile de merge https://github.com/Litarvan/pronote-api/pull/183 (merci encore @Androz2091)

**Comment by madsenfr** [comment]
Maintenant que je sais utiliser pronote-api, que j'ai forké dans madsenfr/pronote-api, pour changer la version node dans package.json, je suis repassé sur Amazon Alexa et `pronote.login` ne prend que 5 s !
Je ne me l'explique pas, mais ça m'arrange.
