### ISSUE TITLE
Ajout du CAS Ile-De-France

### ISSUE THREAD

**Issue by Iltotore** [Litarvan/pronote-api#164]
Récemment, les lycées d'Ile-De-France ont changé le processus d'authentification de leur pronote (pour ceux qui l'ont gardé), ajoutant une étape vers `ent.iledefrance.fr`

Lien présupposé pour le cas: `ent.iledefrance.fr/cas/login?service=<lien du pronote>`

**Comment by ThibautTrarbach** [comment]
Hello,

Ce CAS existe depuis au moins 1 ans et demis.

Cdt
Thibaut

**Comment by Iltotore** [comment]
Alors mon lycée est clairement à la traine...
Merci de la réponse rapide.

**Comment by ThibautTrarbach** [comment]
Je vous confirme, J'ai fini mes études l'année dernière et j'ai eux pendant mes 3 ans d'étude cette ent.

Cdt
Thibaut
