### ISSUE TITLE
Erreur avec les timestamps

### ISSUE THREAD

**Issue by QuentinBubu** [Litarvan/pronote-api#165]
Bonjour,
Le format retourné par l'API pour les dates est-il bien le timestamp?
Car lors du retour de la requête 3 zéros viennent se mettre à la fin du timestamp ce qui fausse les conversions vers une heure compréhensible
Exemple:
`1605600000000` retourne `9/6/52849 8:00:00`
Alors que si l'on enlève les 3 derniers zéros, il retourne la date voulue soit `17/11/2020 8:00:00`.
Merci par avance,
Quentin

**Comment by ThibautTrarbach** [comment]
Yes, c'est un timestamp en node js, donc c'est un timestamp en millisecond, donc c'est totalement normal.

Cdt
Thibaut
