### ISSUE TITLE
AC Poitiers - Educonnect

### ISSUE THREAD

**Issue by goldorakiller** [Litarvan/pronote-api#166]
Depuis peu pour l'académie de Poitiers, il faut passer par un compte Educonnect.
Serais-ce possible d'ajouter cette connexion ?

**Comment by MartinHeywang** [comment]
Bonjour !

Je suis de l'académie de strasbourg (ac-strasbourg) et je dois également passer par Educonnect.
Cependant, _Scolarité Services_ fonctionnent toujours (et comme avant) chez nous.

Pour me connecter, j'ai utilisé mes anciens identifients (ceux que j'utilisais avant, avec *Scolarité Services*), en spécifiant bien le CAS à utiliser.

Cela ne résout pas votre problème, j'en ai conscience, mais en attendant...
