### ISSUE TITLE
Filtre graphl

### ISSUE THREAD

**Issue by Raphelvo** [Litarvan/pronote-api#167]
Bonjour,

Je n'arrive pas a avoir un filtre 'from' to 'to' sur les devoirs pour avec l'interface graphql. Je n'ai que ceux du lendemains.
Voici la requete que j'ai, quelqu'un connaitrait la syntaxe pour demander sur 2 jours par exemple ?
{ homeworks(student:"Prenom NOM") { description, subject, givenAt, for, done }

J'ai fait un petit scripts sur domoticz qui récupère un certains nombre d'information et qui tourne sur mon raspberry 2. Ce n'est pas complet mais si ca peut aider (je viens de passer le repo en public) :
https://gitlab.com/Raphelvo/domoscript/-/blob/master/dzVents/scripts/pronoteStudent1.lua

N'hésitez pas a fermer cette issue si vous voulez; c'est plus une demande de support que je ne sais pas ou poster.

**Comment by ThibautTrarbach** [comment]
Hello, Quel est la requête que vous faite avec les from et to ?

Cdt
Thibaut

**Comment by Raphelvo** [comment]
'{ homeworks(student:"'..student1..'", from:"1605654000", to:"1605826800") { description, subject, givenAt, for, done } }

A mon avis le format de la date est pas bonne ;)

**Comment by ThibautTrarbach** [comment]
Hello,

C'est normal les timestamp ne sont pas au bon format, il fut pas oublier que c'est du node js. Donc c'est en miliseconde.
Seconde info, c'est plus simple de mettre la date comme sa : "11-18-2020"

Cdt
Thibaut

**Comment by Raphelvo** [comment]
D'accord noté, merci encore. C'est bon.  Je ne connais ni json, ni node, ni js, ni graphql mais grâce a votre support ca fini par marcher.
