### ISSUE TITLE
Unknown CAS "tous"

### ISSUE THREAD

**Issue by KintonHiryuu** [Litarvan/pronote-api#17]
Salut ! merci pour cette api très utile, j'ai un petit soucis avec mon "cas"

J'essaie ton api avec un pote, lui code sous python et moi sous nodejs, lui n'as aucun problème avec l'api mais moi, sur W10 (comme lui) ou raspbian 9, peut importe node ou python, j'ai toujours la même erreur : "Unknown CAS 'nomducas'

j'ai essayer avec le mien (ac-rouen) ainsi que 'none', avec les login de mon pote et les miens j'ai cette erreur :

```TypeError: Cannot read property 'access' of undefined
    at init (/home/pi/pronote/pronote-api/src/pronote.js:816:38)
    at login (/home/pi/pronote/pronote-api/src/pronote.js:24:24)
    at Object.fetch (/home/pi/pronote/pronote-api/src/pronote.js:197:15)
    at IncomingMessage.req.on (/home/pi/pronote/pronote-api/index.js:30:33)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Unknown CAS 'none'
```

j'ai regardé les anciennes issues et ait trouvé l'ajout de "console.log(body)" en ligne 28 qui me log :
```{
  "type": "fetch",
  "username": "NOMDUCOMPTE", !
  "password": "PASSWORD", !
  "url": "http://lyc-client.ac-rouen.fr:81/", !
  "cas": "none" // ou ac-rouen selon ce que je mets
}
```
évidemment les entrées finissant par "!" sont censurés

une idée d'où viendrais le problème ?

**Comment by Marineeee** [comment]
Yo, quand je look ton "url" ça pointe pas sur pronote... l'url doit normalement pointer sur pronote exemple : http://79.107.104.226/
Pour moi par exemple, l'url est : https://xxxxx.xxxx.xx/pronote/ ce qui me met sur pronote. 
Chez moi en mettant la bonne url pronote : 
![image](https://user-images.githubusercontent.com/45340378/76705759-a8de3b80-66e2-11ea-9707-40670715b469.png)
En mettant la mauvaise (pas la bonne url / path) :
![image](https://user-images.githubusercontent.com/45340378/76705771-c4e1dd00-66e2-11ea-9baa-66ce8436154a.png)

**Comment by KintonHiryuu** [comment]
justement c'est a cet endroit que c'est étrange : mon ami (a qui j'ai emprunté les identifiants pour les tests) utilise exactement les infos qui sont marqués dans mon message et tout fonctionne pour lui

je vais essayer d'ajouter le /pronote a la fin je te rapelle après; merci a toi

**Comment by Androz2091** [comment]
Yep en fait c'est le catch ici qui est censé gérer le fait que le fichier du cas précisé ne soit pas trouvé qui catch aussi l'erreur du fetch (https://github.com/Litarvan/pronote-api/blob/63df71dfa2745d203be8a8c662a65056d28c639b/src/pronote.js#L824). Tu devrais avoir une erreur plus claire dans la console (du serveur pronote-api).

**Comment by KintonHiryuu** [comment]
j'ai envoyé l'erreur des deux serveurs (python et api) ceci-dit pour l'instant en ajoutant /pronote a la fin du lien ca ne fonctionne toujours pas :/ je vais essayer avec mon établissement a moi lmais j'y crois pas trop

**Comment by KintonHiryuu** [comment]
```{
  "type": "fetch",
  "username": "kinton.hiryuu",
  "password": "PASSWORD",
  "url": "https://0760056y.index-education.net/pronote/",
  "cas": "ac-rouen"
}
TypeError: Cannot read property 'access' of undefined
    at init (/home/pi/pronote/pronote-api/src/pronote.js:816:38)
    at login (/home/pi/pronote/pronote-api/src/pronote.js:24:24)
    at Object.fetch (/home/pi/pronote/pronote-api/src/pronote.js:197:15)
    at IncomingMessage.req.on (/home/pi/pronote/pronote-api/index.js:30:33)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Unknown CAS 'ac-rouen'
```
voila l'erreur avec mon établissement a moi (user/pass censurés)

je note donc la présence du /pronote a la fin de mon lien et cette erreur sors directement de l'api pas de mon programme (api que j'ai re-clonner plusieurs fois et qui est la même que mon ami)

**Comment by KintonHiryuu** [comment]
ok, bon, il se trouve que j'ai trouvé ca, toujors de litarvan (merci beaucoup mec ! t'assures !)
https://www.npmjs.com/package/pronote-lib

et étrangement en utilisant ces infos la depuis mon serveur (sachant que cette api ne fonctionnais pas sur mon serveur) tout fonctionne a merveille, et la chance est vraiment la car c'est en nodejs pour du nodejs sachant que mon projet EST en nodejs :D


merci donc a vous de votre aide, je clos ici même si le problème est pas résolu, et vive nodejs
