### ISSUE TITLE
Lister toute les matières

### ISSUE THREAD

**Issue by JBX028** [Litarvan/pronote-api#170]
Bonjour,

Je cherche un moyen d'extraire et de catégoriser toute les matières d'un établissement mais il semble que ça ne soit pas vraiment possible. J'ai par chance, 2 enfants qui sont dans des établissements différents et j'ai écrit la fonction suivante pour obtenir une liste en demandant les devoirs de toute l'année:

```
async function getListOfSubjects(session) {
    let subjects = []
    const homeworks = await session.homeworks(new Date('2020-09-01'), new Date('2021-09-01'))
    homeworks.forEach(element => subjects.push(element.subject))
    return subjects = [...new Set(subjects)];
}
```

Pour mon premier enfant j'obtiens l'output suivant:

`["FRANCAIS","HISTOIRE-GEOGRAPHIE","ANGLAIS","MATHEMATIQUES","CO INTERVENTION MATHS","CO INTERVENTION FRANCAIS","ECONOMIE-GESTION","SCIENCES","PREVENT.-SANTE-ENV.","Accompagnement Personnalisé","ENS.TECHNOL.PROFESS."]`

et pour mon deuxième enfant :

`["ESPAGNOL LV2","SCIENCES VIE TERRE","ANGLAIS LV1","TECHNOLOGIE","FRANCAIS","SC.PHYSIQ.ET CHIMIQ.","HIST.GEO.EN.MOR.CIV.","MATHEMATIQUES"]`

Je ne connais pas bien comment les matières sont définis dans pronote mais à priori, un établissement est libre de définir sans se baser sur un corpus. Est-ce bien le cas ?

Je suis en train d'écrire une application pour mon google home afin de demander les devoirs et les notes pour mes enfants mais la seule fonction qui pêche c'est lorsque je demande si il y a des devoirs dans une matière car c'est très disparate et qu'aucune liste existe.
Il est possible dans l'api google de définir des "entities" et même de les injecter en début de conversations mais il me faudrait une liste exhaustive ainsi qu'une liste de synonymes basé sur un corpus fermé qui ne semble pas exister dans pronote.

Ma question est la suivante. Est-il possible d'extraire toute les matières ? J'aimerais en savoir un peu plus sur le fonctionnement interne de pronote dans ce domaine afin de voir comment je pourrais avancer sur ce sujet.

Merci

**Comment by JBX028** [comment]
J'ai passé une partie de la soirée à chercher un peu de doc et à priori, la liste est assez libre d'être changé à oa guise de l'établissement:

Les matières sont dans la plupart des cas récupérées d’EDT. Vous pouvez en créer de
nouvelles, notamment si certains services de notation ne correspondent pas à des
cours (enseignement à distance, etc.).
Créer une nouvelle matière
Prérequis Il faut être un utilisateur du groupe Administration.
1. Rendez-vous dans l’onglet Ressources > Matières > Liste.
2. Cliquez sur la ligne de création.
3. Saisissez le libellé de la matière et validez avec la touche [Entrée].
4. Modifiez le code proposé par défaut ou validez directement avec la touche [Entrée].
5. La matière est créée et positionnée à sa place dans la liste en fonction du critère de tri.

**Comment by ThibautTrarbach** [comment]
Hello,

J'ai pas vraiment compris la demande.

Cdt
Thibaut

**Comment by Androz2091** [comment]
Il me semble que c'est pour savoir s'il existe un "endpoint" pour obtenir la liste des matières côté élève autrement qu'en scrawlant l'EDT. Et je ne crois pas.

**Comment by JBX028** [comment]
En effet c'est bien résumé :)
Bonjour je ferme car à priori ce n'est pas possible mais je pense avoir réussi à gérer mon problème en jouant avec les possibilités de l'api google assistant.
Merci
