### ISSUE TITLE
Ajout d'id unique

### ISSUE THREAD

**Issue by ThibautTrarbach** [Litarvan/pronote-api#176]
Suite a nos discussion @Litarvan et moi, nous allons metre des id unique pour chaque info

**Comment by Androz2091** [comment]
Un identifiant unique pour chaque devoir par exemple ? Si oui, comment sera-t-il généré ? Est-ce qu'il sera généré à partir d'informations du devoir (en hashant la date, le contenu, etc.) ou simplement avec un suite de caractère aléatoire ? S'il est généré à partir d'informations du devoir, est-ce qu'il permettra réellement d'identifier un devoir (même si le contenu change par exemple) ?

**Comment by ThibautTrarbach** [comment]
Je sait pas, c'est @Litarvan qui va le faire. Donc il faut voir avec lui.

Cdt
THibaut

**Comment by ThibautTrarbach** [comment]
https://github.com/Litarvan/pronote-api/tree/litarvan/ids

**Comment by ThibautTrarbach** [comment]
Cela fonctionne parfaitement. Actuellement dans une branche a part
