### ISSUE TITLE
Disparition des marks

### ISSUE THREAD

**Issue by Raphelvo** [Litarvan/pronote-api#179]
Depuis  ce lundi 0h00 je n'ai plus aucune note, que ce soit avec le fetch ou le server ql; avez vous remarqué la même chose ?

Note: Je me connecte en tant que parent.

Le fetch me sort ca :
        "marks": {
                "subjects": [],
                "averages": {}
            },

**Comment by Androz2091** [comment]
Bonjour, tout fonctionne pour moi avec une centaine de comptes et de serveurs Pronote différents (des comptes élèves).

Les notes sont bien affichées avec la version web ?

Cela pourrait venir d'un changement de trimestre, ou de quelque chose comme ça je pense. Peut-être que `session.marks('semester');` pourrait résoudre votre problème

**Comment by Raphelvo** [comment]
Oui les notes sont bonne sur le site pronote. J'utilise la commande :
pronote-fetch https://0601766u.index-education.net/pronote/ moncompteparent monmotdepasse hdf parent

Je vais voir comment bricoler le paramètre semester merci pour la piste.

**Comment by Raphelvo** [comment]
J'ai essayé avec period=year (const Type = ['trimester', 'semester', 'year'];) effectivement il semblerais qu'on ai changé de trimester. 😄
