### ISSUE TITLE
"error": "Cannot read property 'V' of undefined"

### ISSUE THREAD

**Issue by Marineeee** [Litarvan/pronote-api#18]
Salut, soucis lors du fetch des infos : 
![image](https://user-images.githubusercontent.com/45340378/76705822-2f931880-66e3-11ea-82b4-32766ec9fecf.png)
Lors d'un simple login, 0 soucis, mais lors de fetch impossible de lire la valeur de "V" car non définie... ( deuxième issue sur ce problème d'ailleurs ). Pour préciser, j'utilise une config CAS privée.

**Comment by Marineeee** [comment]
Requête json envoyée avec POSTMAN sur le serveur local
![image](https://user-images.githubusercontent.com/45340378/76705859-91538280-66e3-11ea-9764-e0ca42e3e69c.png)

**Comment by Androz2091** [comment]
Il y a déjà une issue ouvert à ce sujet (#15) 😅
