### ISSUE TITLE
Ajouter le CAS Atrium (PACA)

### ISSUE THREAD

**Issue by Nathn** [Litarvan/pronote-api#180]
Bonjour j'aurai besoin du CAS de la région Sud/PACA : Atrium
L'URL : [https://www.atrium-sud.fr/connexion/login](https://www.atrium-sud.fr/)
Merci d'avance !

**Comment by ThibautTrarbach** [comment]
Hello,

Le cas est déjà disponibles en beta dans l'api.

Cdt
Thibaut
