### ISSUE TITLE
Avoir la liste de tous les éléves d'une classe

### ISSUE THREAD

**Issue by Spokaren** [Litarvan/pronote-api#182]
Bonjour,
J'aimerais savoir si c’était possible de lister tous les élèves de sa classe.
Merci d'avance.

**Comment by ThibautTrarbach** [comment]
Peux on avoir un peux plus d'information ?
Quel type de compte pour fetch ?
Avoir quel information ?
etc etc etc

Cdt
Thibaut

**Comment by Spokaren** [comment]
Je parle de lister le nom et le prénom de tous les éléves de sa classe

**Comment by Androz2091** [comment]
J'imagine que tu veux faire ça avec un compte élève ?

**Comment by ThibautTrarbach** [comment]
@Androz2091 D'ou la question que j'ai poser. Et dont j'ai pas reçu toute les réponse

**Comment by Spokaren** [comment]
oui avec un compte éléve

**Comment by ThibautTrarbach** [comment]
@Spokaren il y a une raison ? Car je n'en vois pas l'utilité actuellement.

Cdt
Thibaut

**Comment by Androz2091** [comment]
Bien que je ne pense pas que ce soit possible, cela peut être utile (pour de la gestion de contacts sur téléphone par exemple). Et je ne pense pas que la question de l'utilité doit vraiment se poser. Si l'API privée de Pronote le permet, on le supporte, et si elle ne le permet pas la question s'arrête là non ?

**Comment by ThibautTrarbach** [comment]
@Androz2091 je suis d'accord, il faut que je regarde, mais je pense pas. Car j'ai jamais vu les nom et prénoms de mes collègues sur mes ancien établissements.

**Comment by Androz2091** [comment]
Je pense aussi. Peut-être lors de messages groupés à une classe en regardant dans la liste des destinataires mais bon c'est pas terrible comme solution... et encore faut-il avoir un message

**Comment by ThibautTrarbach** [comment]
Pas de nouvelle,

Je close, il pourras rouvrir ou faire une nouvelle demande
