### ISSUE TITLE
Ajouter les contenus du cours au donnés récupérables.

### ISSUE THREAD

**Issue by Iridium77Ir** [Litarvan/pronote-api#188]
Dans cette période de confinement générer une liste des codes zoom depuis des devoirs à été mon "use case" primaire de l'api. Certains professeurs mettent les codes dans le contenu du cours cependant. 
Pourrait-t-on ajouter les contenus du cours au donnés récupérables?

**Comment by ThibautTrarbach** [comment]
Hello,

I know you don't speak French, and I confess that I don't understand anything. (Imperfect translation).
I'd advise you to ask a second message in English.

Cdt
Thibaut

**Comment by Androz2091** [comment]
@Iridium77Ir les contenus des cours sont récupérables en utilisant `session.contents()`, le résultat ressemble à celui de `session.homeworks()`, si c'est de ça dont tu as besoin

**Comment by Iridium77Ir** [comment]
Merci, c'est exactement ça!
