### ISSUE TITLE
Erreur 404 sur le lien du schéma complet des requêtes GraphQL

### ISSUE THREAD

**Issue by busybox11** [Litarvan/pronote-api#194]
Sur le README, un lien permet d'afficher le schéma complet des requêtes du serveur GraphQL, mais le fichier n'existe pas (donc erreur 404).
![image](https://user-images.githubusercontent.com/29630035/101068254-c4eb7b00-3598-11eb-9c89-6a75b31b8a0b.png)

**Comment by ThibautTrarbach** [comment]
Hello,

Voila c'est mis a jours.

Cdt
Thibaut
