### ISSUE TITLE
Paramètres des fonctions de la librairie

### ISSUE THREAD

**Issue by madsenfr** [Litarvan/pronote-api#201]
Bonjour,

Quels sont les paramètres et leurs formats des fonctions homeworks, timetable et marks ?
Ou bien où les trouver ?
J'ai bien essayé de passer 2 arguments `from `et `to `à timetable, d'abord en string au format `YYYY-MM-DD`, puis en objet JS `Date`, puis même avec `moment.js`, mais rien n'y fait, ça me retourne un tableau vide, alors que si je ne mets aucun argument je récupère quelques prochains cours.

Comment procéder, SVP ?

**Comment by Androz2091** [comment]
Bonjour,
Les objets `Date` devraient fonctionner. Personnellement j'utilise ça pour récupérer les devoirs :
```js
session.homeworks(new Date(Date.now()), session.params.lastDay)
```

ça me permet de récupérer tous les devoirs jusqu'à la fin de l'année

**Comment by madsenfr** [comment]
Merci @Androz2091, ça semble fonctionner, mais concernant le 2ème paramètre je pense qu'il faudrait un véritable objet date pour contrôler la date de fin de période.
