### ISSUE TITLE
Support des serveurs Pronote sans certificat SSL

### ISSUE THREAD

**Issue by Androz2091** [Litarvan/pronote-api#207]
Bonjour,
J'ai actuellement un problème pour obtenir le CAS de cet ENT : http://81.194.39.137:8088/pronote/eleve.html. La méthode `getCAS()` ne fonctionne pas, j'imagine que c'est soit du au fait que c'est une IP (même si pour certaines IP ça fonctionne), soit du au fait que le serveur ne dispose pas de certificat SSL. Est-ce que quelqu'un a plus d'informations ?

Ce serveur Pronote correspond au LYCEE GENERAL ET TECHNOLOGIQUE JACQUES CALLOT - VANDOEUVRE LES NANCY (054). Un élève m'a prêté ses identifiants et j'ai pu tester de me connecter via mon navigateur, et ça fonctionne bien. En supposant que le cas est `ac-nancy-metz` (ce dont je ne suis pas sur), impossible de se connecter via la librairie (j'ai toujours l'erreur `Wrong user credentials`...)

**Comment by ThibautTrarbach** [comment]
Hello,

Pronote supporte les serveur sans certificat.
la n'est pas le problèmes. Je pense plutôt a des problèmes de redirection ou autre

Ps : sa serait cool d'etre sur du CAS.

Cdt
Thibaut

**Comment by Androz2091** [comment]
@ThibautTrarbach le cas c'est celui-ci https://cas.monbureaunumerique.fr/login?service=http:%2F%2F81.194.39.137:8088%2Fpronote%2Feleve.html. Et c'est justement parce que je n'arrive pas vraiment à savoir s'il est supporté ou non que je me tourne vers vous avec cette issue...
Ça a l'air d'être monbureaunumerique mais visiblement il n'y a pas de cas "monbureaunumérique"

**Comment by ThibautTrarbach** [comment]
C'est bien ce cas, mais tu est sur de l'academie ?

Cdt
Thibaut

**Comment by Androz2091** [comment]
Non justement, comment peut-on l'obtenir?

**Comment by ThibautTrarbach** [comment]
En testant tu choisi quel choix sur le bureaux numérique ?

**Comment by Androz2091** [comment]
Educonnect (https://cdn.discordapp.com/attachments/788097510379618374/788144874716135494/unknown.png)

**Comment by ThibautTrarbach** [comment]
Alors c'est normal on gère pas educonnect pour cette académies. La seul que l'on gère et qui est en test, c'est toutatice.

Donc celle de nancy c'est celle dans élèves ou parent

**Comment by Androz2091** [comment]
D'accord, et c'est possible de la gérer ?

**Comment by ThibautTrarbach** [comment]
Yes, tu peux test de faire un truc sur la copy de toutatice. 
Mais j'ai pas encore eux le temps.

Cdt
Thibaut

**Comment by Androz2091** [comment]
J'ai le même problème avec ce serveur : https://0350700w.index-education.net/pronote/, l'élève se connecte via Educonnect et cela ne semble pas être supporté (pourtant c'est avec le cas toutatice)..

**Comment by ThibautTrarbach** [comment]
Ok, Tu veux que je delette ton commentaire ou tu veux juste le laisser masqué ?

**Comment by Androz2091** [comment]
C'est bon, j'ai fait exprès de le cache 👍 
par contre on a toujours le gars qui attend pour son cas non supporté 😅 
![Capture d’écran 2020-12-22 à 18 03 11](https://user-images.githubusercontent.com/42497995/102914044-011b4880-4480-11eb-8d61-98093a6c082d.png)

**Comment by ThibautTrarbach** [comment]
Heuuu, excuse moi de te le dire. Mais j'ai pas 100h de temps surtout avec les fête de noel.

Si il veux que sa aille plus vite il peux le faire. Mais actuellement j'ai que très peux de temps... 
Donc sa arrivera quand j'aurais le temps et la motivation.

Cdt
Thibaut

**Comment by ThibautTrarbach** [comment]
Oups tromper de button

**Comment by Androz2091** [comment]
Je comprends, pas de problème je saurai le faire patienter :grin:

**Comment by ThibautTrarbach** [comment]
...
