### ISSUE TITLE
Académie de Rennes non compatible

### ISSUE THREAD

**Issue by ZKillou** [Litarvan/pronote-api#21]
Bonjour, j'ai essayer de me connecter à Pronote depuis le NPM package pronote-lib qui utilise votre API mais je n'ai pas réussi à me connecter depuis l'Académie de Rennes. J'ai aussi essayer "toutatice" mais ça na pas fonctionné... Pourriez-vous m'aider ?

**Comment by Litarvan** [comment]
Bonjour, peux-tu me montrer ton erreur ?

**Comment by ZKillou** [comment]
UnhandledPromiseRejectionWarning: Not logged in

**Comment by wow0000** [comment]
Cette erreur là viens de mon API et signifie que la connexion à pronote n'a pas encore été effectué, d'ou la présence d'un callback. Son problème original est que malgré que l'académie de Renne sois noté comme compatible il n'y a pas de fichier "ac-rennes" et il semblerait que toutatice ne fonctionne pas non plus.

**Comment by 3l0w** [comment]
Salut j'ai une autre erreur je suis sur toutatice mais j'ai cette erreur:
`Error: getaddrinfo ENOTFOUND www.toutatice.frctrl`
cela viendrai de cette ligne la:
https://github.com/Litarvan/pronote-api/blob/master/src/cas/toutatice.js#L29

**Comment by LeGmask** [comment]
Dans les fait l'erreur provient du fait que toutatice a changer de module d'authentification pour utiliser le module educonnect a la place de celui développer initialement 😉.

**Comment by 3l0w** [comment]
ha vu sous cet angle c'est vrai que c'est logique.
il fonctionne ton patch?

**Comment by Litarvan** [comment]
Salut, peux-tu me dire si tu as toujousr ce problème avec la nouvelle version ?

**Comment by ZKillou** [comment]
Bonjour !
Je testerai cela lorsque j'aurai reçu mon nouveau code pronote (car je change d'établissement donc je n'ai plus accès à mon ancien compte)
Je vous ferais part de mon résultat.

**Comment by 3l0w** [comment]
```
TypeError: getParams is not a function
    at login (G:\pronote-api\src\cas\toutatice.js:15:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getStart (G:\pronote-api\src\auth.js:71:12)
    at async Object.login (G:\pronote-api\src\auth.js:17:19)
    at async login (G:\pronote-api\src\server\auth.js:17:23)```

**Comment by 3l0w** [comment]
j'ai fix l'erreur:
[api.js#L105](https://github.com/Litarvan/pronote-api/blob/527275cd4a5618845aaedaa1537064bc64ccda9c/src/cas/api.js#L105)
```js
module.exports = {
    submitForm,
    getParams,
    getDOM,
    extractStart
};
```

**Comment by 3l0w** [comment]
mais j'ai une autre erreur : ```
{
  "message": "getaddrinfo ENOTFOUND www.toutatice.frctrl",
  "name": "Error",
  "stack": "Error: getaddrinfo ENOTFOUND www.toutatice.frctrl\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)",
  "config": {
    "url": "https://www.toutatice.frCtrl",
    "method": "post",
    "data": "0=undefined&1=undefined&2=undefined&3=undefined&4=undefined&5=undefined",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/x-www-form-urlencoded",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0",
      "Cookie": "IDP_JSESSIONID=DA0CD165ED867EB59507DF31E1F1D383; SpCookie=PRIPASP2; BIGipServer~PROD-DMZ~PRIPASP_1-2=rd100o00000000000000000000ffffc0a8db03o80; JSESSIONID=CEACD7B5D2585F34AADD98BBB459BFC0; WAYF-COOKIE-HOST=wayf-1; Persistence=!zC7wi/r1yfmHSle7Y9PnjC+lK0ZjPabLUBRnIGdVW/GpCVrnkSboXXm5qDQ7vrIIz01SWJ/CGymJ6gkKJKkYHXKdLFaidE2MieZqtcQyckaI",
      "Content-Length": 71
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxRedirects": 0
  },
  "code": "ENOTFOUND"
}```

**Comment by Litarvan** [comment]
Le CAS ayant fondamentalement changé, il n'est dorénavant plus supporté par l'API

**Comment by Litarvan** [comment]
Alors surprise j'ai pu reprendre le code d'un autre CAS au même fonctionnement, je l'ai donc remis et ça _devrait_ fonctionner. Pour tester, il faut que l'un de vous dézippe https://github.com/Litarvan/pronote-api/archive/master.zip dans son dossier node_modules/pronote-api/ et se connecte avec comme CAS 'toutatice' et ses identifiants educonnect.

**Comment by 3l0w** [comment]
```
{ code: 3, message: 'Wrong user credentials' }
```

**Comment by Litarvan** [comment]
Est-ce que tu as bien des identifiants educonnect ?

**Comment by 3l0w** [comment]
yep je les ai tester juste avant de repondre sur educonnect

**Comment by 3l0w** [comment]
Si tu est disponible je peut t'aidé a test
Mon discord: Fl0w#3841

**Comment by NooodyFR** [comment]
Même problème de mon côté, il me retourne "Mauvais identifiants" alors que les identifiants sont corrects.

J'ai regardé dans les requêtes, et il arrive pourtant a trouver le lien de mon pronote, qui n'est affiché que sur mon "bureau virtuel" (valeur de "url + account.value + '.html'" dans le educonnect.js).

De plus, à la fin de l'authentification, lorsqu'il veut accéder à Pronote, la page passe par un intermédiaire qui affiche "Authentification en cours..." et qui ne contient pas PRONOTE (extractStart dans le api.js), donc il renvoie l'erreur des mauvais identifiants

J'espère pouvoir être utile :)

**Comment by Litarvan** [comment]
Okdac c'est bien ce que je pensais, merci de ce debug détaillé ! J'aurais besoin que tu me contactes sur Discord à Litarvan#0420 pour que je te fasse faire un test mais ça devrait pas être très dur :)

**Comment by ZKillou** [comment]
Bonjour ! Je suis désolé de ne pas avoir répondu car cette année, on ne passe plus par Toutatice mais Pronote directement...
Désolé...

**Comment by trmaud** [comment]
Hello,

Votre problème est résolut ?

Cdt
Thibaut

**Comment by bugsounet** [comment]
bonjour, il semblerai que non ...
je viens d'avoir un retour sur un de mes user que l'api de toutatice retourne `mauvais identifiants`...
Je vais essayer d'avoir le max d'info d'ici quelques jours

**Comment by ThibautTrarbach** [comment]
Ok hésite pas a me faire des retours,

@Litarvan est pas mal occuper en ce moment. 
Je fait donc mon possible pour tout géré.

Cdt
Thibaut

**Comment by NooodyFR** [comment]
Note : L'authentification bloque sur une page HTML qui n'est pas gérée par l'API, il faudrait ajouter son support (il y a un gros bout de code en JS qui montre comment l'authentification est faite dans cette page)

**Comment by ThibautTrarbach** [comment]
Possible de me send la page avec sont lien. Voir si c'est possible de recup des identifiant pour test.

Ps : Mon Discord : "Thibaut Black#0001"

Cdt
Thibaut

**Comment by 3l0w** [comment]
Cela a été fixé ?

**Comment by ThibautTrarbach** [comment]
Toujours pas, on attend @Litarvan qui doit être en partiel actuellement.

Cdt
Thibaut

**Comment by ebanDev** [comment]
Bonjour, j'ai aussi un problème avec Toutatice je ne sais pas si c'est lié... (si ce n'est pas le cas je m'en excuse) quand je me connecte j'ai le droit à un "curl: (52) Empty reply from server"...
Ma requête : 
`👌  eban <~> 
   ❯❯  curl -X POST -H "Content-Type: application/json" -d '{
    "url": "http://03XXXXX.index-education.net/",
    "username": "XXXXX",
    "password": "XXXXX",
    "cas": "toutatice"
}' http://10.0.0.11:8000/auth/login`
Je précise que j'utilise GraphQL

**Comment by 3l0w** [comment]
@ebanDev J'ai une bonne nouvelle pour toi j'ai fait un fix: #172

**Comment by ebanDev** [comment]
Génial !! Tu penses que ce sera updaté dans le repo pip dans combien de temps ?

**Comment by ebanDev** [comment]
Je vais tester et je te dit si ca marche pour moi

**Comment by ebanDev** [comment]
Si tu préfères, j'ai un discord : Eban#9456

**Comment by 3l0w** [comment]
Rien de plus simple: 
```bash
npm i https://github.com/3l0w/pronote-api.git
```

**Comment by ebanDev** [comment]
Ok je test ca, merci :)

**Comment by ThibautTrarbach** [comment]
Merge a l'instant dans la master, je vous laisse faire les test.

Cdt
Thibaut

**Comment by madsenfr** [comment]
Bonjour,
Je viens de tester et j'obtiens encore le message "Mauvais identifiants".
Avec les id de démo ça fonctionne.
J'ai vérifier mon url et mes id et bien décommenter /*, cas*/ dans l'exemple pour l'initialiser avec "toutatice".
Par contre, j'utilise un fork https://github.com/madsenfr/pronote-api où la seule différente est la version mini de node.js à 10.21.0, qui ne provique pas d'erreur par ailleurs.
Merci pour vos efforts, je suis à votre dispo pour tester.

**Comment by ThibautTrarbach** [comment]
Peux on voir ta config ?

Cdt
Thibaut

**Comment by madsenfr** [comment]
Bien sûr, mais qu'entends-tu pas config, tu veux avoir quoi comme infos ?

- Node 10.23.0
- url = "https://0561598h.index-education.net/pronote/";
- username = [compte educonnect testé];
- password = [mdp educonnect testé];
- cas = 'toutatice';
- const session = await pronote.login(url, username, password, cas);

**Comment by 3l0w** [comment]
Passe discord si tu veut je vais t'aider
fl0w#3841

**Comment by madsenfr** [comment]
Je ne connais pas Discord, je suis sur la version en ligne : Ragnar56#8172

**Comment by madsenfr** [comment]
Suite à l'aide de 3l0w, la conclusion c'est que ça vient de ma version de Node.js utilisée (10.23.0).
Pour être précis l'identification directement via pronote fonctionne, mais en passant par un CAS ça ne fonctionne plus.
Je n'ai pas de message d'erreur, juste une exception au login.

**Comment by NooodyFR** [comment]
Educonnect étant acutellement en maintenance, il se peut qu'il y ait des erreurs lors de la connexion via celui ci :)

**Comment by ThibautTrarbach** [comment]
Dispo dans l'api depuis peux.

Je close
