### ISSUE TITLE
Manque d'exemple.

### ISSUE THREAD

**Issue by Nirbose** [Litarvan/pronote-api#210]
Je trouve qu'il manque beaucoup d'exemple surtout pour les Date.
Donc serrais t'il possible de rajouter un fichier **.md** avec des exemples de toutes les fonction possible ?

**Comment by ThibautTrarbach** [comment]
Hello,

Je te laisse faire un PR, car actuellement j'ai pas le temps.

Cdt
Thibaut

**Comment by Nirbose** [comment]
Désolé mais j'ai pas tout compris :
Que voulais vous dire en disant : PR et Cdt ?

**Comment by Androz2091** [comment]
PR est l'acronyme de `Pull Request`, en bref c'est une fonctionnalité de Git qui permet de suggérer des modifications à un projet. Pour résumer sa phrase, si tu penses que ce projet manque d'exemples, tu peux en écrire toi-même et demander à ce qu'on les ajoute à la librairie mais lui ne le fera pas faute de temps.

Et Cdt c'est juste cordialement 😅

**Comment by ThibautTrarbach** [comment]
Parfais merci d'avoir répondu @Androz2091 

Cdt
Thibaut

**Comment by Nirbose** [comment]
Ah ok désolé ^^" je ne connaissais pas c'est "raccourci ". merci de me l'avoir dis et oui du moins si j'y arrive ^^"
