### ISSUE TITLE
Problème de récupération d'emploi du temps

### ISSUE THREAD

**Issue by StanByes** [Litarvan/pronote-api#212]
Bonsoir j'ai un problème depuis au moins deux mois, qui est que la récupération de l'emploi du temps est défectueuse car l'api récupère les cours de 15H et 16H alors qu'il est 19H le jour même et il ne récupère pas les cours de l'après-midi le lendemain.

**Comment by Androz2091** [comment]
Salut 👋
C'est le fonctionnement attendu de la part de l'API, récupérer les cours du jour actuel si aucune date n'est spécifiée 😉
Tu peux utiliser le code suivant pour obtenir les cours du lendemain passé 18h :
```js
const from = new Date().getHours() > 18 ? new Date(Date.now() + 24 * 60 * 60 * 1000) : new Date();
const timetable = session.timetable(from);
```

**Comment by StanByes** [comment]
D'accord ça fonctionnait avant merci de votre part 👍

**Comment by StanByes** [comment]
Je viens d'essayer mais il me met toujours à "20H45" le cour de 15 à 17 et il ne me met pas le dernier cours de demain.

**Comment by StanByes** [comment]
Rebonsoir, je viens d'essayer il me met toujours à "20H51" le cours de 15 à 17 d'aujourd'hui et il ne me met pas le dernier cours de demain

**Comment by Androz2091** [comment]
C'est étrange ça 🤔
Tu as bien la dernière version de la librairie ? Si oui on peut t'aider plus facilement ici si tu veux : https://discord.gg/9cXkwDp

**Comment by StanByes** [comment]
Oui j'ai bien la dernière version et je suis sur le Discord sous le nom de StanByes :)

**Comment by StanByes** [comment]
Je viens de voir sur le Discord on a découvert que le problème venait de l'heure du serveur sur lequel était héberger mon app
