### ISSUE TITLE
Retour différents des données du site

### ISSUE THREAD

**Issue by suiramdev** [Litarvan/pronote-api#214]
J'ai remarqué en essayant l'API que les données qu'il me retourne (comme `session.absences() --> absences`) sont différentes de ceux visible sur le site pronote de l'établissement:

Les données obtenu en console.log:
`pronote.login("http://195.221.62.29/pronote/", "marius.nouchet1", "kfyz9NFPG", "ac-nantes")
    .then(session => {
        session.absences().then(res => console.log(res.absences));
    })`
![image](https://user-images.githubusercontent.com/71449142/103892781-74fa5980-50ec-11eb-8ace-1c1d2259bc4b.png)

Les données sur le site: 
![image](https://user-images.githubusercontent.com/71449142/103893017-d4f10000-50ec-11eb-9dbd-a952984b18c9.png)

Peut être que le soucis vient de mon établissement aussi ?

**Comment by ThibautTrarbach** [comment]
Hello,

je vois pas de problèmes.

Cordialement
Thibaut

**Comment by suiramdev** [comment]
Bien, il n'y à pas les 10 absences mais seulement 4 dans la table récupéré ?

**Comment by suiramdev** [comment]
Ooooh, pardon j'ai pas fais attention, de base la fonction absences() retourne seulement les absences du mois ?

**Comment by ThibautTrarbach** [comment]
Yes

**Comment by suiramdev** [comment]
Ok ! Désolé alors j'suis passé à côté de ca, je suis bête 😅

**Comment by suiramdev** [comment]
On peux delete carrément l'issue au lieu de le close ?
J'ai mis mes logins dans une partie du code sur les versions précédente 😅
