### ISSUE TITLE
ENT

### ISSUE THREAD

**Issue by konoashi** [Litarvan/pronote-api#215]
Comment on peut se connecter si on a pas d'identifiants pronote car c'est l'ent qui intégre directement notre compte pronote ?

**Comment by Cobbrou** [comment]
Tu dois utiliser ton compte CAS ( Donc ton compte ENT ) pour pouvoir te connecter, le [readme.md](https://github.com/Litarvan/pronote-api/blob/master/README.md) explique comment cela marche.

**Comment by konoashi** [comment]
ok par contre juste pour modif le host pronote-api-server PORT HOST il faut le faire apres npm run pronote.js ?

**Comment by konoashi** [comment]
car quand je fais pronote-api-server 12333 localhost ca me dit
Uncaught SyntaxError: Unexpected number

**Comment by Cobbrou** [comment]
J'ai pas trop compris ta question ? Tu parles de l'URL de pronote ?

**Comment by konoashi** [comment]
nan l'host 127.0.0.1:80 fait une erreur donc j'essaye de changer de host pour me mettre sur localhost

**Comment by Androz2091** [comment]
@konoashi, pourquoi tu n'utilises pas plutôt le client simplement sans ouvrir de serveur HTTP ? (comme dans le README)

**Comment by konoashi** [comment]
Car je fais un bot discord

**Comment by Androz2091** [comment]
Ah oui ? Et tu le fais en Javascript ton bot Discord ? Si tu veux on peut t'aider ici https://androz2091.fr/discord, on fait pas mal de bots là bas 😉

**Comment by konoashi** [comment]
Pour le bit en lui même je gère c'est loin d'être mon premier mais par contre pour l'intégration de la requête....
