### ISSUE TITLE
Erreur lors de la requête

### ISSUE THREAD

**Issue by ALittlePatate** [Litarvan/pronote-api#217]
Quand je lance le programme mis en exemple pour tester l'api, que je remplace les identifiants par les miens que je remplace l'url par : https://0332722e.index-education.net/pronote/eleve.html je n'ai pas de message d'erreur mais les détails de la requête.

Tout est là : 

 { Error: getaddrinfo EAI_AGAIN 0332722e.index-education.net 0332722e.index-education.net:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: '0332722e.index-education.net',
  host: '0332722e.index-education.net',
  port: 443,
  config:
   { url:
      'https://0332722e.index-education.net/pronote/eleve.html?login=true',
     method: 'get',
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent':
         'Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0',
        'Content-Type': '',
        Cookie: '' },
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 0,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     maxBodyLength: -1,
     maxRedirects: 0,
     validateStatus: [Function: validateStatus],
     data: undefined },
  request:
   ClientRequest {
     _events:
      [Object: null prototype] { response: [Function], error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: false,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        alpnProtocol: null,
        authorized: false,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: true,
        _handle: null,
        _parent: null,
        _host: '0332722e.index-education.net',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData:
         'GET /pronote/eleve.html?login=true HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0\r\nContent-Type: \r\nCookie: \r\nHost: 0332722e.index-education.net\r\nConnection: close\r\n\r\n',
        _pendingEncoding: 'latin1',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 6,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: false,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        alpnProtocol: null,
        authorized: false,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: true,
        _handle: null,
        _parent: null,
        _host: '0332722e.index-education.net',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData:
         'GET /pronote/eleve.html?login=true HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0\r\nContent-Type: \r\nCookie: \r\nHost: 0332722e.index-education.net\r\nConnection: close\r\n\r\n',
        _pendingEncoding: 'latin1',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 6,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0,
        [Symbol(connect-options)]: [Object] },
     _header:
      'GET /pronote/eleve.html?login=true HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0\r\nContent-Type: \r\nCookie: \r\nHost: 0332722e.index-education.net\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     insecureHTTPParser: undefined,
     path: '/pronote/eleve.html?login=true',
     _ended: false,
     res: null,
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] {
        accept: [Array],
        'user-agent': [Array],
        'content-type': [Array],
        cookie: [Array],
        host: [Array] } },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON] }

**Comment by ALittlePatate** [comment]
ps : j'ai la même erreur avec l'url "mon.lyceeconnecte.fr" qui est celle que je devrait utiliser (pareil avec le CAS : lyceeconnecte)

**Comment by Androz2091** [comment]
Bonjour, 
Je ne suis pas sur que le problème vienne réellement de la mais peux tu essayer avec `https://0332722e.index-education.net/pronote/` (sans `eleve.html?login=true`)

**Comment by ALittlePatate** [comment]
> Bonjour,
> Je ne suis pas sur que le problème vienne réellement de la mais peux tu essayer avec `https://0332722e.index-education.net/pronote/` (sans `eleve.html?login=true`)

J'ai essayé mais j'ai une erreur "Mauvais identifiants" sauf que mes id sont corrects :/

**Comment by Androz2091** [comment]
Tu peux m'envoyer le code complet de ton programme (en remplaçant les identifiants par des XXXX mais en gardant le plus d'infos possible)

**Comment by ALittlePatate** [comment]
> Tu peux m'envoyer le code complet de ton programme (en remplaçant les identifiants par des XXXX mais en gardant le plus d'infos possible)

`const pronote = require('pronote-api');

// Exemple
const url = 'mon.lyceeconnecte.fr';
const username = 'xxx';
const password = 'xxx';
const cas = "ac-bordeaux";

async function main()
{
    const session = await pronote.login(url, username, password, cas);
    session.setKeepAlive(true);

    console.log(session.user.name); // Affiche le nom de l'élève
    console.log(session.user.studentClass.name); // Affiche la classe de l'élève
    
    const timetable = await session.timetable(); // Récupérer l'emploi du temps d'aujourd'hui
    const marks = await session.marks(); // Récupérer les notes du trimestre
    
    console.log(`L'élève a ${timetable.length} cours aujourd'hui`); 
    console.log(`et a pour l'instant une moyenne de ${marks.averages.student} ce trimestre.`);
    
    // etc. les fonctions utilisables sont 'timetable', 'marks', 'contents', 'evaluations', 'absences', 
    // 'homeworks', 'infos', et 'menu', sans oublier les champs 'user' et 'params' qui regorgent d'informations.
}

main().catch(err => {
    if (err.code === pronote.errors.WRONG_CREDENTIALS.code) {
        console.error('Mauvais identifiants');    
    } else {
        console.error(err);
        console.error('Error here !');
    }
});`

**Comment by Androz2091** [comment]
Pas de problème. Voilà ce qui me semble être correct (bien que je ne puisse pas le garantir en testant) : https://hastebin.androz2091.fr/icacakamiq.js.

**Comment by ALittlePatate** [comment]
> Pas de problème. Voilà ce qui me semble être correct (bien que je ne puisse pas le garantir en testant) : https://hastebin.androz2091.fr/icacakamiq.js.

ça marche ! Merci à toi !

**Comment by Androz2091** [comment]
Parfait, bonne fin de soirée 👍

**Comment by madsenfr** [comment]
Juste pour info, parce que j'ai eu un problème similaire.
Sur l'académie de Rennes, mes identifants parents ne passaient pas alors qu'avec les identifiants de mon enfant ça fonctionne.
Étant donné que Pronote fonctionne bien par ailleurs avec mes identifiants je n'ai pas pensé à ça tout de suite.
