### ISSUE TITLE
Changer le port de l'api (pas en GraphQL)

### ISSUE THREAD

**Issue by HyperFreeze** [Litarvan/pronote-api#226]
Bonjour, je souhaite mettre en place l'api pronote  sur mon bot discord et je fais déjà tourner un site sur le port 80 de mon serveur... Comme prévu l'api envoie une erreur en disant qu'elle ne peut pas se connecter au 127.0.0.1:80 .
Je me demandais si l'on peut changer le port de l'api ?
**Merci d'avance**

**Comment by Androz2091** [comment]
Sachant que 80 n'est pas le port par défaut du serveur, si tu n'as pas explicitement défini 80 comme port quelque part ça me parait étrange que tu obtiennes cette erreur

Si tu fais ton bot Discord simplement en JavaScript tu peux aussi utiliser le client simplement, ou directement utiliser ce projet : https://github.com/Androz2091/pronote-bot-discord.

**Comment by HyperFreeze** [comment]
En fait j'ai l'erreur ECONNREFUSED avec can't connect to 127.0.0.1:80
Donc j'ai supposé que ça vient du port 80 qui n'est pas libre

**Comment by Androz2091** [comment]
> En fait j'ai l'erreur ECONNREFUSED avec can't connect to 127.0.0.1:80
Donc j'ai supposé que ça vient du port 80 qui n'est pas libre

Ok, non pas du tout, c'est simplement que la requête a échoué, parce que je pense que le serveur pronote-api est toujours sur le port par défaut, soit `21727`.

Est-ce que tu peux essayer de faire une requête vers `127.0.0.1:21727` au lieu de `127.0.0.1:80`?

**Comment by HyperFreeze** [comment]
Et comment je fais ça ?
