### ISSUE TITLE
Erreur "code 5" en se connectant via ENT (ac-orleans-tours)

### ISSUE THREAD

**Issue by Firokat** [Litarvan/pronote-api#229]
En utilisant le code exemple du  README, l'API renvoit un message d'erreur.
```js
{ code: 5, message: 'Session has expired due to inactivity or error' }
```

Une idée d'où cela pourrait venir ?

PS : Tout fonctionne bien avec le serveur de démo, donc cela doit venir du serveur Pronote de mon établissement

**Comment by ThibautTrarbach** [comment]
Tu te connect avec quel site pour ton académie ?

Cdt
Thibaut

**Comment by Firokat** [comment]
C'est avec netocentre, l'ENT de la région Centre-Val de Loire
[Lien ici si besoin](https://lycees.netocentre.fr/portail/f/welcome/normal/render.uP)

**Comment by kyesuwu** [comment]
Si tu as toujours le même problème c'est peut-être que les requêtes vont trop vite, j'ai l'impression qu'il y a une sorte de rate limit qui fait expirer la session quand trop de requêtes sont reçues. Je ne peux malheureusement pas donner plus d'informations car j'ai du mal à comprendre comment cette limite fonctionne et je suppose qu'elle varie entre établissements.

**Comment by Firokat** [comment]
Pourquoi pas, mais comment résoudre ce problème du coup ? Mettre un délai entre chaque requête ? Si oui, comment faire ? Mais merci pour les informations.

**Comment by kyesuwu** [comment]
Honnêtement je ne sais pas vraiment comment résoudre le problème à 100%, des délais avec setTimeout ou autre devraient faire l'affaire (j'ai aussi trouvé [p-ratelimit](https://www.npmjs.com/package/p-ratelimit) qui pourrait aider) mais après je ne sais pas vraiment ce qui compte comme du "spam" pour Pronote et je pense que ça dépend des établissements donc je peux pas trop t'aider pour les valeurs désolé

**Comment by Firokat** [comment]
OK je regarderai ça quand j'aurai le temps. Merci de ton aide

**Comment by busybox11** [comment]
Bonjour, 
Une update sur cette issue ?
Une personne utilisant mon bot a la même erreur.
Merci d'avance !

**Comment by Firokat** [comment]
Bonsoir, j'ai essayé d'implémenter le limit rate mais sans résultat, sinon pas plus d'info.

**Comment by LeMustelide** [comment]
Bonjour, quelqu'un a-t-il réussi depuis ? 
merci.

**Comment by Firokat** [comment]
Non j'utilise pronotepy depuis et ça fonctionne.

**Comment by LeMustelide** [comment]
MERCI !!!
