### ISSUE TITLE
Académie de Orléans Tours incompatible

### ISSUE THREAD

**Issue by SPILEURFR** [Litarvan/pronote-api#23]
Salut !
Pourrais-tu ajouter l'académie Orléans Tours stp ?
Car on passe par "Net'O Centre", c'est pas une connexion directe

**Comment by Niromash** [comment]
Le cas de l'académie d'Orléans-Tours marche très bien

**Comment by SPILEURFR** [comment]
Peut-être pour toi mais mon lycée passe par Net'O Centre, c'est pas une connexion directe donc je sais pas si ça vas fonctionner

**Comment by Niromash** [comment]
Mais tu sais que son API a cette académie

**Comment by Niromash** [comment]
Mon lycée passe pas netocentre et ça fonctionne très bien
