### ISSUE TITLE
Professeur EDT

### ISSUE THREAD

**Issue by TapsHTS** [Litarvan/pronote-api#232]
Peut on récupérer quand les professeurs sont absent ?

**Comment by Nirbose** [comment]
Salut !
Alors Non tu ne peux pas. Du moins pas avec cette version d'API

**Comment by ThibautTrarbach** [comment]
Hello, Oui il est possible, il suffit de lire les bandeaux des cours :) Par contre de souvenir chaque école en fait que a sa tête pour la formulation

**Comment by Androz2091** [comment]
On ne peut pas utiliser lesson.isAway?

**Comment by ThibautTrarbach** [comment]
On peux, mais de souvenir c'est pas spécifique au prof absent

**Comment by Androz2091** [comment]
Ah oui, c'est tous les cours annulés. Mais je pense que c'est ce que voulait @TapsHTS, savoir quand un cours est annulé
je viens d'implémenter ça sur mon bot discord https://github.com/Androz2091/pronote-bot-discord et ça a l'air de fonctionner

**Comment by TapsHTS** [comment]
@Androz2091 y a t'il un moyen de tester cette fonctionnalité ? Au lieu d'attendre qu'un professeur soit absent ?

**Comment by Androz2091** [comment]
Si tu veux tu peux te connecter sur le site de démo (https://demo.index-education.net/pronote/eleve.html) avec le bot
