### ISSUE TITLE
Obtenir la valeur de la note (Exemple: Mathématiques, votre note: 20/20)

### ISSUE THREAD

**Issue by Kalaghar** [Litarvan/pronote-api#237]
Bonjour, je n'arrive pas à trouver comment obtenir la valeur d'une note, je vois la moyenne de la classe, la note minimale et maximale mais pas la valeur de notre note . 
Est-ce possible ?

**Comment by Kangourou812** [comment]
Bonjour, @Kalaghar as-tu trouvé la solution a ton problème ? Car j'ai la meme !
