### ISSUE TITLE
Erreur lors de la connexion

### ISSUE THREAD

**Issue by Kangourou812** [Litarvan/pronote-api#238]
Bonjour,
Je ne comprend pas mon erreur, je me connecte via : cas.ent.auvergnerhonealpes.fr et avec le CAS : ac-grenoble voici mon code `const pronote = require('pronote-api');

// Exemple
const url = 'cas.ent.auvergnerhonealpes.fr';
const username = '********';
const password = '********!';

async function main()
{
    const session = await pronote.login(url, username, password, "ac-grenoble");
    
    console.log(session.user.name); // Affiche le nom de l'élève
    console.log(session.user.studentClass.name); // Affiche la classe de l'élève
    
    const timetable = await session.timetable(); // Récupérer l'emploi du temps d'aujourd'hui
    const marks = await session.marks(); // Récupérer les notes du trimestre
    
    console.log(`L'élève a ${timetable.length} cours aujourd'hui`); 
    console.log(`et a pour l'instant une moyenne de ${marks.averages.student} ce trimestre.`);
    
    // etc. les fonctions utilisables sont 'timetable', 'marks', 'contents', 'evaluations', 'absences', 
    // 'homeworks', 'infos', et 'menu', sans oublier les champs 'user' et 'params' qui regorgent d'informations.
}
main().catch(err => {
    if (err.code === pronote.errors.WRONG_CREDENTIALS.code) {
        console.error('Mauvais identifiants');    
    } else {
        console.error(err);
    }
});`
et voici mon erreur `TypeError: Cannot set property 'value' of null
    at login (/Users/damien/Desktop/Pronote/node_modules/pronote-api/src/cas/generics/kdecole-wayf.js:31:62)
    at processTicksAndRejections (<node_internals>/internal/process/task_queues.js:93:5)
    at async getStart (/Users/damien/Desktop/Pronote/node_modules/pronote-api/src/auth.js:67:12)
    at async login (/Users/damien/Desktop/Pronote/node_modules/pronote-api/src/auth.js:19:19)
    at async main (/Users/damien/Desktop/Pronote/pronote.js:10:21) {stack: 'TypeError: Cannot set property 'value' of nul…sers/damien/Desktop/Pronote/pronote.js:10:21)', message: 'Cannot set property 'value' of null'}`
Cordialement

**Comment by ThibautTrarbach** [comment]
Hello, l'URL doit être celui de ton Pronote et non celui de ton cas


Cordialement
Thibaut

**Comment by Kangourou812** [comment]
Bonjour,
J'ai changé l'URL de "cas.ent.auvergnerhonealpes.fr" en : "https://www.ent.auvergnerhonealpes.fr/" il m'affiche l'erreur : `Error: Request failed with status code 404`
Cordialement

**Comment by ThibautTrarbach** [comment]
Quand tu est sur ta page Pronote, tu peux me send le lien dans on navigateurs ?

Cdt
Thibaut

**Comment by Kangourou812** [comment]
Voila : https://clg-belledonne.ac-grenoble.fr/pronote/eleve.html?identifiant=*************

**Comment by ThibautTrarbach** [comment]
Alors l'url sera : https://clg-belledonne.ac-grenoble.fr/pronote/

**Comment by Kangourou812** [comment]
Ouiiiiii merci beaucoup !!!!

**Comment by Kangourou812** [comment]
Bonjour,
Je souhaiterais obtenir un renseignement sur comment accéder aux objets renvoyés par cette commandes : `console.log(await (await session.marks()).subjects);` , elle ma renvoie : `name: 'ANGLAIS',
    averages: { student: 17.94, studentClass: 13.35, max: 19.69, min: 5.93 },
    color: '#ED679B',
    marks: [ [Object], [Object], [Object], [Object], [Object], [Object] ]`
Cordialement
