### ISSUE TITLE
Cannot find module 'punycode'

### ISSUE THREAD

**Issue by Kangourou812** [Litarvan/pronote-api#240]
Bonjour,
J'aimerai beaucoup utiliser le NPM Pronote-Api sur mon site web wix, ce qui est normalement possible avec wix velo.
J'ai donc ajouté ce code 
`import { login } from 'pronote-api';

async function main()
{
    const session = await login("***", "**", "**"/*, cas*/);
    // ... Voir l'exemple JavaScript
}`
et il me renvoie `Cannot find module 'punycode'`
je ne voie pas le raport entre Pronote-Api et Punycode.
Pouvez-vous m'éclairer sur ce sujet ?
Cordialement

**Comment by ThibautTrarbach** [comment]
Hello,

A tu des nouvelle ? car cela n'est pas dans le code de l'api.

Cordialement
Thibaut

**Comment by Kangourou812** [comment]
Ok merci je vais voir si le bug vient d'ailleurs !
