### ISSUE TITLE
[FR] Plusieurs sessions supportées en simultanées ?

### ISSUE THREAD

**Issue by euzzeud** [Litarvan/pronote-api#243]
Bonjour,
J'ai pour projet de dev un bot Discord permettant de consulter Pronote.

Seulement, je me posais la question s'il était possible de gérer plusieurs connexions en simultanées?

Cordialement

**Comment by TapsHTS** [comment]
Je crois que faire est interdit

**Comment by Androz2091** [comment]
Bonjour
Oui c'est possible

**Comment by euzzeud** [comment]
Dac merci! :)
