### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by euzzeud** [Litarvan/pronote-api#246]
Bonjour j'ai cette erreur qui s'affiche quand souhaite me connecter : **Error: connect ECONNREFUSED 127.0.0.1:80**

**Comment by ThibautTrarbach** [comment]
Tu test un serveur Pronote en local ?

Cdt
Thibaut

**Comment by euzzeud** [comment]
Oui sur un ordi sous Windows 10

**Comment by ThibautTrarbach** [comment]
Donc tu a un serveur pronote local a l'endroit ou tu test l'api ?

**Comment by ThibautTrarbach** [comment]
L'api se connect a un serveur pronote, tu a celui de demo pour test.

**Comment by euzzeud** [comment]
Ah oui d'accord non j'ai mes login avec ent  ile de france

**Comment by euzzeud** [comment]
Mon ent avait visiblement un problème... problème résolu !

**Comment by bougimax** [comment]
Salut je rencontre le même problème que toi, qu'as tu fait pour le régler?

**Comment by bougimax** [comment]
C'est bon c'est réglé ;)
