### ISSUE TITLE
Serait-il possible d'afficher les moyennes des 3 trimestres ?

### ISSUE THREAD

**Issue by euzzeud** [Litarvan/pronote-api#247]
Sous forme d'array ou autre par exemple ?

Cordialement :)

**Comment by kyesuwu** [comment]
Bonjour, 
En temps normal session.marks() permet de récupérer les notes d'un trimestre avec l'argument period, bien que de mon côté cela ne fonctionne plus depuis quelques temps.
Je ne peux malheureusement pas donné plus d'informations pour l'instant, je n'ai pas encore vérifié si le problème venait de mon établissement ou si il s'agissait d'un changement dans l'api.

**Comment by euzzeud** [comment]
Pas grave merci quand même ^^
