### ISSUE TITLE
UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by Zentae** [Litarvan/pronote-api#25]
Bonjour, bonsoir. Il y'a quelque moment de cela j'ai rencontré un problème avec "pronote-api"

` Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1058:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:636:8)`

Pour plus de précision j'utilise le client java fourni pas Litarvan et mes identifiants sont tous correct et je n'utilise pas de CAS. Dites moi si vous voulez le code java :D

PS: Petite précision il me dit 'Unknown CAS none"

**Comment by Litarvan** [comment]
Salut, peux-tu réessayer avec la nouvelle version ?

**Comment by Litarvan** [comment]
Je ferme pour inactivité, si tu as toujours le même problème n'hésite pas à réouvrir l'issue
