### ISSUE TITLE
Comment récupérer la dernière note ?

### ISSUE THREAD

**Issue by Kangourou812** [Litarvan/pronote-api#252]
Bonjour je n'ai pas réussi à trouver comment récupérer la dernière note mais J'arrive à récupérer les notes pour le trimestre en cours.
Mon but est de faire qu'à chaque nouvelle note je reçoive un sms avec la note via l'api très simple de Free !
Cordialement￼

**Comment by ThibautTrarbach** [comment]
Hello,

Tu regarde le la dernier note en date et ensuite tu vérifie si c'est la même ou pas.

Cordialement 
Thibaut

**Comment by Kangourou812** [comment]
Merci je n'y avais pas pensé !￼￼
