### ISSUE TITLE
Instance Pronote

### ISSUE THREAD

**Issue by FunkyFight** [Litarvan/pronote-api#260]
Bonjour, puis-je avoir plus de détail sur qu'est ce qu'une instance pronote ? D'ailleurs, je reçois aussi cette erreur : connect ECONNREFUSED 127.0.0.1:80. Que faire pour y remédier ?

**Comment by ThibautTrarbach** [comment]
Hello,

C'est erreur n'est pas du a l'api mais a une erreur de configuration,
Je te laisse nous donné la config que tu a fait avec l'api.

Cordialement 
Thibaut

**Comment by FunkyFight** [comment]
Bonjour,
Quand tu parles de configuration, tu parles de quoi exactement ? Les paramètres que j'ai mis dans la méthode pronote#login ?

**Comment by FunkyFight** [comment]
Bonjour, puis-je avoir une réponse s'il vous plaît ?

**Comment by ThibautTrarbach** [comment]
Tu utilise quel fonction de l'API ainsi que ce que tu lui a configurer pour te connecter a ton compte pronote.

Cordialement
Thibaut
