### ISSUE TITLE
Compte Pronote professeur bloqué par un code PIN

### ISSUE THREAD

**Issue by Dalvii** [Litarvan/pronote-api#270]
Bonjour, certains compte pronote professeur sont sécurisé avec un code pin.
Est-ce que vous pensez avoir une solution?
Merci.
![image](https://user-images.githubusercontent.com/26835772/113619643-873b5380-9659-11eb-8232-6cb0d974378d.png)

**Comment by ThibautTrarbach** [comment]
Hello,

Nous somme au courant, mais l'api ne supporte pas encore les compte professeur.
Donc cela nous impacte pas encore.

Cordialement
Thibaut
