### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by Raskc** [Litarvan/pronote-api#276]
J'ai trouver cette api et je la trouve très intéressante !
Néanmoins j'ai rarement coder en JS du coup je suis un peu perdus.
J'ai finalement réussis à trouver mon url avec mon CAS pour l'ent etc.
Cependant quand j'exécute mon code qui est exactement celui du read.me mais avec mes informations.

J'obtiens l'erreur suivante:
Error: connect ECONNREFUSED 127.0.0.1:80

J'ai essayer de scroll un peu mais je ne trouve pas ma solution donc si quelqu'un pourrait m'éclairer ce serait sympa !

**Comment by ThibautTrarbach** [comment]
Peux tu nous montrée comment tu a configurer ton api.

Cordialement
Thibaut

**Comment by RaskUwU** [comment]
Voici le code que j'utilise:
![image](https://user-images.githubusercontent.com/56470884/115020305-b30cd380-9eba-11eb-99fe-401278cc185b.png)

Pour la config je ne sais pas vraiment ce que je suis censé montrer. J'ai vraiment juste
utiliser npm pour télécharger l'api. Puis j'ai ouvert Visual Code pour faire un petit test.

**Comment by ThibautTrarbach** [comment]
Comme tout le monde, ton url est pas celle de l'ent mais celle de Pronote.

Cordialement
Thibaut

**Comment by Steelpex** [comment]
> J'ai trouver cette api et je la trouve très intéressante !
> Néanmoins j'ai rarement coder en JS du coup je suis un peu perdus.
> J'ai finalement réussis à trouver mon url avec mon CAS pour l'ent etc.
> Cependant quand j'exécute mon code qui est exactement celui du read.me mais avec mes informations.
> 
> J'obtiens l'erreur suivante:
> Error: connect ECONNREFUSED 127.0.0.1:80
> 
> J'ai essayer de scroll un peu mais je ne trouve pas ma solution donc si quelqu'un pourrait m'éclairer ce serait sympa !

Salut ! Ca à rien à avoir avec ta question c'est te demander est ce que tu peux m'envoyer les dossier "pronote-api" qui contient tous les autres fichiers stp ?
