### ISSUE TITLE
Cannot read property 'action' of undefined

### ISSUE THREAD

**Issue by fantomitechno** [Litarvan/pronote-api#277]
Bonjour, j'essaye d'utiliser le module node et quand je lance mon programme, il me renvoie une erreur qui viendrait du module
```
[...]\test-pronote-api>node index
TypeError: Cannot read property 'action' of undefined
    at submitForm ([...]\test-pronote-api\node_modules\pronote-api\src\cas\api.js:8:66)
    at login ([...]\test-pronote-api\node_modules\pronote-api\src\cas\generics\kdecole-educonnect.js:20:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getStart ([...]\test-pronote-api\node_modules\pronote-api\src\auth.js:67:12)
    at async login ([...]\test-pronote-api\node_modules\pronote-api\src\auth.js:19:19)
    at async main ([...]\test-pronote-api\index.js:11:21)
```

J'essaye d'utiliser le cas `monbureaunumerique-educonnect` et l'url `cas.monbureaunumerique.fr`

Merci d'avance à ceux qui pourront m'éclairer

**Comment by ThibautTrarbach** [comment]
Hello,

Ton programme resemble a quoi ?

Cdt
Thibaut

**Comment by fantomitechno** [comment]
```js
const pronote = require('pronote-api')

// Exemple​
const url = "cas.monbureaunumerique.fr";
const username = "XXXXX";
const password = "XXXX";
const cas = "monbureaunumerique-educonnect"

async function main()
{
    const session = await pronote.login(url, username, password, cas);
    
    console.log(session.user.name); // Affiche le nom de l'élève
    console.log(session.user.studentClass.name); // Affiche la classe de l'élève
    
    const timetable = await session.timetable(); // Récupérer l'emploi du temps d'aujourd'hui
    const marks = await session.marks(); // Récupérer les notes du trimestre
    
    console.log(`L'élève a ${timetable.length} cours aujourd'hui`); 
    console.log(`et a pour l'instant une moyenne de ${marks.averages.student} ce trimestre.`);
    
    // etc. les fonctions utilisables sont 'timetable', 'marks', 'contents', 'evaluations', 'absences', 
    // 'homeworks', 'infos', et 'menu', sans oublier les champs 'user' et 'params' qui regorgent d'informations.
}

main().catch(err => {
    if (err.code === pronote.errors.WRONG_CREDENTIALS.code) {
        console.error('Mauvais identifiants');    
    } else {
        console.error(err);
    }
});```
soit juste une copie de l'exemple donné

**Comment by ThibautTrarbach** [comment]
C'est normal ton url doit être celui de ton pronote que tu est sur la page de ton pronote et non le lien de ton ENT

Cdt
Thibaut

**Comment by fantomitechno** [comment]
aaah je me suis fait avoir par les CAS ^^'

**Comment by fantomitechno** [comment]
du coup je dois mettre ma page pronote soit [...].fr/pronote ?

**Comment by ThibautTrarbach** [comment]
Yes,

**Comment by fantomitechno** [comment]
Celà me renvois "mauvais identifiants" 😕 
Est ce que le fait que je sois obliger d'utiliser un compte educonnect doit me faire changer de lien ?

**Comment by ThibautTrarbach** [comment]
Cela depend de comment tu te connect

**Comment by fantomitechno** [comment]
avec l'api ou à la main ?

**Comment by ThibautTrarbach** [comment]
A la main, pas quel site tu passe pour allez a l'ent

**Comment by fantomitechno** [comment]
dans l'ordre : 
cas3.e-lyco.fr
educonnect.education.gouv.fr
et enfin pronote

**Comment by ThibautTrarbach** [comment]
Tu arrive a te connecter via ce lien ? : 
https://cas.monbureaunumerique.fr/login

Cordialement
Thibaut

**Comment by fantomitechno** [comment]
accès non autorisé

**Comment by ThibautTrarbach** [comment]
Ok donc tu utilise le mauvais CAS.

Et je trouve auccun CAS avec ce lien, tu peux me donner l'url exacte que je regarde ?

Cordialement
Thibaut

**Comment by fantomitechno** [comment]
ceci ? http://pronote.lyc-briand-44.ac-nantes.fr/pronote

**Comment by ThibautTrarbach** [comment]
Tu passe par le quel ? :
![image](https://user-images.githubusercontent.com/30575266/115267730-cbd6ec80-a139-11eb-9a4a-e63692b937ff.png)

**Comment by fantomitechno** [comment]
educonnect

**Comment by fantomitechno** [comment]
Du coup, j'ai trouvé comment me connecter : j'utilise du coup mon compte ATEN (qui est censé être désactivé) et cela marche bien
