### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by yanivdouieb** [Litarvan/pronote-api#278]
Bonjour, 
J'ai un problème avec l'api, j'ai l'erreur suivant : Error: connect ECONNREFUSED 127.0.0.1:80

J'ai pourtant bien vérifier l'URL, rein n'y change...
Voici le code : 
  const url = 'ent.parisclassenumerique.fr'
    const username = 'XXXX'
    const password = 'XXXX'
    const cas = 'parisclassenumerique'

    async function main() {
      const session = await pronote.login(url, username, password, cas);

      console.log(session.user.name);
      console.log(session.user.studentClass.name);

      const timetable = await session.timetable();
      const marks = await session.marks();

      console.log(`L'élève a ${timetable.length} cours aujourd'hui`);
      console.log(
        `et a pour l'instant une moyenne de ${marks.averages.student} ce trimestre.`
      );
    }

    main().catch((err) => {
      if (err.code === pronote.errors.WRONG_CREDENTIALS.code) {
        console.error("Mauvais identifiants");
      } else {
        console.error(err);
      }
    });`

et voici l'erreur complète : 
 Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80,
  config: {
    url: 'parisclassenumerique/eleve.html?login=true',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0',
      'Content-Type': '',
      Cookie: ''
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    maxRedirects: 0,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      response: [Function],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: Socket {
      connecting: false,
      _hadError: true,
      _parent: null,
      _host: 'localhost',
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 8,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: 'GET parisclassenumerique/eleve.html?login=true HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0\r\n' +
        'Content-Type: \r\n' +
        'Cookie: \r\n' +
        'Host: localhost\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _pendingEncoding: 'latin1',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(async_id_symbol)]: 63,
      [Symbol(kHandle)]: null,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'GET parisclassenumerique/eleve.html?login=true HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0\r\n' +
      'Content-Type: \r\n' +
      'Cookie: \r\n' +
      'Host: localhost\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: 'parisclassenumerique/eleve.html?login=true',
    _ended: false,
    res: null,
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'localhost',
    protocol: 'http:',
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      'content-type': [Array],
      cookie: [Array],
      host: [Array]
    }
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

Merci d'avance pour votre aide

**Comment by ThibautTrarbach** [comment]
Hello,

Vous avez regarder les 3 autre issue comme la votre ?
Et oui c'est votre URL qui est incorrect.

Cordialement
Thibaut

**Comment by yanivdouieb** [comment]
Oui, j'ai regardé, mais je ne sais pas quoi mettre à la place

**Comment by ThibautTrarbach** [comment]
C'est l'url de ton pronote pas de ton ent

**Comment by yanivdouieb** [comment]
Comment ?

**Comment by yanivdouieb** [comment]
L'url que j'utilise pour me connecter c'est : https://ent.parisclassenumerique.fr/auth/login/

**Comment by ThibautTrarbach** [comment]
Yes, mais c'est pas l'url de ton pronote, c'est l'url que tu a quand tu est sur ta page pronote

l'url que tu ma donner c'est ton ent

Cdt
Thibaut

**Comment by yanivdouieb** [comment]
Comment je fais pour récupérer l'url de mon pronote ?

**Comment by ThibautTrarbach** [comment]
Tu va sur pronote et tu regarde l'url de la page quand tu est dessus.

**Comment by yanivdouieb** [comment]
https://ent.parisclassenumerique.fr/welcome
C'est l'URL quand je suis connecté

**Comment by ThibautTrarbach** [comment]
Met une copy d'ecrant de a quoi resemble ta page pour voir si c'est pronote ou pas.

**Comment by yanivdouieb** [comment]
Je crois pas que c'est Pronote
![Capture d’écran 2021-04-17 à 22 48 01](https://user-images.githubusercontent.com/76172599/115126404-08d2a000-9fcf-11eb-9942-a34445fe5a30.png)

**Comment by ThibautTrarbach** [comment]
Sa c'est pas pronote

**Comment by yanivdouieb** [comment]
Dans votre liste de CAS, il y a cette ENT

**Comment by yanivdouieb** [comment]
ENT "Paris Classe Numerique" (CAS : parisclassenumerique, URL : "ent.parisclassenumerique.fr")

**Comment by ThibautTrarbach** [comment]
Yes, c'est un ENT, qui te permet de te connecter a Pronote, si tu a pas Pronote, sa te sert a rien.

Cordialement
Thibaut

**Comment by yanivdouieb** [comment]
Okay... Merci beaucoup 🔥
