### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined 

### ISSUE THREAD

**Issue by ZeAdam** [Litarvan/pronote-api#279]
Bonjour,
Merci beaucoup pour cette API, qui est vraiment très complète.
Lorsque j'essaye de récupérer les leçons à l'aide de `session.contents()`, j'obtiens l'erreur suivante:
```
TypeError: Cannot read property 'name' of undefined
    at contents (C:\wamp64\www\hub2\node_modules\pronote-api\src\fetch\contents.js:37:28)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async main (C:\wamp64\www\hub2\pronote.js:23:22)
```
Après débogage, je pense que la raison pour laquelle cette erreur survient est parce qu'il n'est pas obligé au professeur de rentrer le contenu d'un cours: il peut mettre une pièce jointe sans rien indiquer. C'est justement sur un de ces cours que le blocage se fait.

Merci de corriger l'erreur au plus vite, en testant par exemple si la constante `content` contient bien le contenu requis.

**Comment by ThibautTrarbach** [comment]
C'est merge.

Cordialement
Thibaut
