### ISSUE TITLE
Ajout des modes prof, direction ou viescolaire

### ISSUE THREAD

**Issue by denis-b** [Litarvan/pronote-api#28]
Bonjour, et bravo pour ce travail !
En tant que développeur de [SambaEdu](https://sambaedu.org), je m'intérroge sur la possibilité d'utiliser l'api pour récupérer directement les données de pronote pour synchroniser les comptes utilisateur, et éventuellement les emplois du temps pour permettre l'allumage programmé des ordinateurs.  Le mode viescolaire serait idéal pour cela car il donne accès à l'ensemble des données. 

 Y a-t-il quelque part des explications sur la structure des données, ou doit-on procéder en reverse engineering par analyse des communications entre le navigateur et le serveur ?

**Comment by exybore** [comment]
Bonjour, je me permet de relancer l'issue car je m'intéresse aussi à la récupération de toutes les données dans le cadre d'un projet avec mon lycée.

**Comment by trmaud** [comment]
Hello,
Je travaille actuellement sur l'api (Je crée un plugin domotique l'utilisant sur la solution Jeedom).
Je travaille avec le créateur de l'api à la création de plusieurs fonctions.
Je voudrais bien vous fournir ce que vous voulez. Mais je suis actuellement dans l'incapacité de le faire. Le créateur et moi-même somme des élèves. Nous n'avons donc aucun accès à un compte du type professeur ou vie scolaire. Nous sommes donc actuellement dans l'incapacité de vous crée les fonctions associer à ce type de compte.

Cordialement
Thibaut

Ps : dans le cadre de la création de mon plugin, je suis en discussion avec Index Education pour avoir un environnement Pronote complet de test.

**Comment by StoneSet** [comment]
@trmaud Il me semble qu'il existe une preview de pronote prof, dirlo etc
En ligne et sans inscription : https://www.index-education.com/fr/pronote-info191-demo-des-espaces-web-et-mobile.php

**Comment by trmaud** [comment]
Ok je ne savais pas je vais regarder, je revient vers vous dès que j'ai du temps.

Serait il possible de me dire ce que vous voulez recup ?

Cdt
Thibaut

**Comment by denis-b** [comment]
Bonjour,
 
pour le mode viescolaire, voici les identifiants du site de demo officiel : 
 ```
       "username" => "demonstration2",
        "password" => "pronotevs",
        "url" => "https://demo.index-education.net/pronote/",
        "cas" => "viescolaire"
``
il faut ajouter un fichier viescolaire dans cas/ avecc viescolaire.html comme url.

Je vais faire un pull request de mes changements.

le login fonctionne : 

```
---> Pronote API HTTP Server working on 127.0.0.1:21727
'demonstration2' for 'https://demo.index-education.net/pronote/' is using viescolaire login
Successfully logged user 'demonstration2' in 0.554s
TypeError: Cannot read property '0' of undefined
    at Object.fetch (/var/www/pronote-api/src/pronote.js:207:51)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```
Notre objectif est de pouvoir récupérer les emplois du temps des salles, ainsi que le services des profs.
J'ai commencé à repérer les éléments à interroger dans l'interface qui m'interessent dans mais le problème vient du menu "emploi du temps" sur le bandeau, qui permet d'aaccéder aux sous menus, "emplois du temps profs", salles... , qui n'existe pas en mode élève ou parent, et donc qui n'est pas pris en compte  par le code actuel, et je n'ai pas trop eu le temps de chercher comment le gérer. On tombe ensuite sur un select avec lea liste des profs, salles etc... il faut probablement boucler là dessus.

**Comment by denis-b** [comment]
plus exactement les données sont accessibles sur la page d'accueil :
icone maison , 
puis
bouton page d'accueil, data_genre=7
puis
planning des professeurs :   data_genre=169
planning des salles : data_genre=172

**Comment by trmaud** [comment]
Ok pas de problème, mais pour info ton cas ne te sert plus a rien ;).

J'ai mis dans ma dernière version un nouveau paramètres qui permet de choisir sont mode (parents, élève, et bientôt vie scolaire et prof.)

A ce que je comprends vous avec déjà créé des choses ? Ou alors vous êtes toujours bloqué ?.

Cdt
Thibaut

**Comment by denis-b** [comment]
oui, là c'etait juste l'extrait de mon code pour les logins viescolaire.  j'avais bricolé un peu pour essayer d'extraire les emplois du temps en mode viescolaire, mais j'avais laissé en standby depuis un moment. Je ne suis pas un expert en node, et donc j'attendais que quelqu'un de plus calé se penche sur le problème. Il y a probablement la question des dates à régler, comme c'est fait pour l'EDT en mode élève. 

Moi ce qui m'intéresse c'est : 
- de récupérer l'occupation des salles par jour en json si possible, pour pouvoir dans sambaedu allumer/éteindre les postes.
- récupérer lecontenu de chaque classes et groupes.  Ceci peut être fait soit en passant par l'emploi du temps, soit en bouclant sur toutes les classes/groupes (data_genre=105 "Liste des élèves" ) ou professeurs (data_genre=123 "Liste des professeurs"). 

Le mode viescolaire est le mieux adapté pour cela, il est possible de faire un compte viescolaire en consultation, cela ne consomme pas de licence, et limite les risque de sécu si il est utilisé pour s'authentifier sur l'api.

**Comment by trmaud** [comment]
Ok, je vois votre point de vue. Cela vous gêne si le plugin récupérer 1 semaine au lieux d'un jour ?

Cdt
Thibaut

**Comment by denis-b** [comment]
non, au contraire, c'est même mieux.  De toutes façons derriere il faudra refactoriser pour avoir juste les différences sur  les infos classe et groupes pour mettre à jour l'annuaire AD. 

Tant qu'à faire si  les menus  cantine et le fil d'info sont dispos  comme en mode élève tant mieux.

**Comment by trmaud** [comment]
Il sont disponible, si l'établissements le met a jours, et pour l'instant j'en ai vu très peux ;)

Sa risque de prendre du temps. Je pense réécrire l'api pour qu'elle soit plus claire et surtout avoir des fichier diffèrent en fonction du mode de connexion.

Cdt
Thibaut

**Comment by denis-b** [comment]
Dans un premier temps si j'ai juste accès au planning  semaine de tous les profs je m'en contenterai, cela me permettra de travailler sur la synchro AD, les élèves des groupes sonrt dedans il me semble. 

De toute façon les pages classe/groupe et professeurs ne sont pas très utilles il n'y a pas les infos d'appartenance aux groupes.

L'info intéressante, c'est celle qui est sur obtenue avec data_genre=169 "Planning des professeurs" , en ayant cliqué sur afficher la liste des eleves. si il est possible d'avoir le code minimal pour pouvoir récupérer les données brutres, derrière je peux aider.


En tous cas si tu as besoin d'aide, ou de tests sur un "vrai" pronote en production n'hésite pas à demander.

**Comment by denis-b** [comment]
Finalement j'ai trouvé comment récupérer les infos dont j'ai besoin. Il faudrait se mettre d'accord sur une architecture d'API commune, afin de pouvoir fusionner facilement les différentes fonctions.

**Comment by denis-b** [comment]
Bonjour, j'ai finalement réussi à implémenter les fonctions qu'il m'intéressaient en mode VS : 
 - liste des classes et groupes,
 - listes des eleves et profs pour un groupe ou classe,
 - emploi du temps des salles du jour courant.

Je me suis basé sur le code existant, je nettoie quelques trucs, est je soumets le patch.

**Comment by denis-b** [comment]
J'avais fait ceci, cela fonctionnait en 2019 mais cela ne fonctionne plus avec la version 2020... 
https://github.com/denis-b/pronote-api/commit/010aeeea0277d3e20abc34b2a1cdf2e82c318de3#diff-7cf503bfc1cce00aca6423d473b8ffc1
Je peux essayer de porter sur  le code à jour dans le même style que ce que vous faites, dites moi.

**Comment by trmaud** [comment]
Je vais le faire? mais pour l'instant j'attend @Litarvan, il doit dev le serveur pour recup les donné.
Mais pour l'instant il est malade. 
Donc je patiente depuis 1 semaine

Cdt
Thibaut

**Comment by denis-b** [comment]
Ok, pour le moment le code est dèja fonctionnel, ou il manque des trucs ?

**Comment by denis-b** [comment]
SI je comprends bien l'auth directe est opérationnelle, c'est bien cela ?

**Comment by Litarvan** [comment]
Ca fait beaucoup de requêtes 🤔 ça devrait être possible d'implémenter tout ça rapidement ! Je pense changer un peu le système qui gère les différentes types de comptes avant pour simplifier ça.

Pour l'instant de fonctionnel on a l'auth, les devoirs, l'emploi du temps, les notes, les compétences, les absences et le menu de la cantine. Le reste arrive bientôt (mais comme a dit Thibaut je suis malade pour l'instant donc en pause pour quelques jours).

**Comment by denis-b** [comment]
Bonjour, en regardant le code, je ne vois pas la possiblilité de connexion vie scolaire. Ce n'est pas encore possible ?
Je peux aider si il faut ajouter les structures de donées m'intéressant dans ce mode.

**Comment by Litarvan** [comment]
Bonsoir ! 

La rentrée nous a un peu ralenti mais on travaille dessus :) vu qu'on nous a demandé aussi les comptes parents et professeurs, j'essaie de les enchaîner. Les comptes parents sont déjà terminés sur la branche `litarvan/accounts` donc je pense que les comptes VS seront les prochains.

On vous tient au courant !

**Comment by denis-b** [comment]
Bonjour, nous avons pas mal avancé au niveau de SambaEdu, avec notamment une intégration de la visioconférence BBB et d'un serveur Guacamole pour l'accès distant aux machines. Pour le moment nous somme intégrés sur l'ENT IDF, qui dispose d'une API ouverte, mais qui ne propose pas l'appartenance aux groupes ni les emplois du temps. Du coup l'intégration Pronote apparaît comme la meilleure voie pour pouvoir accéder à ces infos.  Nous pouvons financer le développement, contactez moi pour qu'on en discute.

**Comment by ThibautTrarbach** [comment]
@denis-b le problèmes est pas l'argent, mais le temps. Je suis étudiant comme @Litarvan. Donc on dev e fonction de notre temps a droite a gauche.

Mais je le remonte dans ma todo. Par contre je ne peux vous donné de délais de mon coté.

Cdt
Thibaut

**Comment by JBX028** [comment]
> Bonjour, nous avons pas mal avancé au niveau de SambaEdu, avec notamment une intégration de la visioconférence BBB et d'un serveur Guacamole pour l'accès distant aux machines. Pour le moment nous somme intégrés sur l'ENT IDF, qui dispose d'une API ouverte, mais qui ne propose pas l'appartenance aux groupes ni les emplois du temps. Du coup l'intégration Pronote apparaît comme la meilleure voie pour pouvoir accéder à ces infos. Nous pouvons financer le développement, contactez moi pour qu'on en discute.

Bonjour.....malgré mes recherches sur internet, impossible de trouver des informations sur une api ouvert ENT IDF. Pouvez-vous partager un peu plus de détails sur ce sujet ?
Merci

**Comment by ThibautTrarbach** [comment]
@JBX028 je pense que l'api est pas ouverte, la personne qui fait la demande, est un des effectif de samba EDUC. Et donc c'est eux qui fournisse le logiciel de gestion du Park informatique de beaucoup d'etablisement

**Comment by ThibautTrarbach** [comment]
@denis-b, je vois avec @Litarvan, mais j'ai peux être une proposition pour vous.

Cdt
Thibaut

**Comment by JBX028** [comment]
> @JBX028 je pense que l'api n'est pas ouverte, la personne qui fait la demande (denis), est un des effectifs de samba EDUC.
> Et donc ce sont eux qui fournissent le logiciel de gestion du Park informatique de beaucoup d'établissements. Je pense qu'il ont accès a l'api

Ah ok... merci :)

**Comment by denis-b** [comment]
@JBX028  L'API de l'ENT IDF, et sûrement d'autres est basée sur ent-core : 
http://entcore.org/#/documentation/index
Si on n'est pas allergique à Java, on trouve pas mal de choses dans les tests unitaires.  
Pour beaucoup de fonctions il faut disposer d'un rôle  d'administrateur local ENT, mais malgré tout un simple compte utilisateur peut faire des choses.  
Voici par exemple ce qu'on fait pour les modifs de comptes utilisateurs : 
https://gitlab.sambaedu.org/sambaedu/se4/-/blob/master/sources/var/www/sambaedu/includes/ent.inc.php vers la ligne 312

**Comment by JBX028** [comment]
Merci beaucoup pour toute ces informations @denis-b 
Je vais regarder tout ça ce week end :)

**Comment by ThibautTrarbach** [comment]
Hello, 
@denis-b,  serait-il possible d'avoir un moyen de communiqué avec vous ?

Cdt
Thibaut

**Comment by denis-b** [comment]
bonsoir, désolé de ne pas avoir répondu plus tôt.
demain on fait une réunion avec les devs sambaedu. Si vous voulez nous rejoindre un moment sur la visio : https://visio.sambaedu.org/b/lau-v67-gj9
sinon mon mail : denis.bonnenfant   AT diderot.org

**Comment by ThibautTrarbach** [comment]
Hello,

Moi sa me gène pas. Donc a demain, vous avez une heure plus précise ou pas ?

Cdt
Thibaut

**Comment by denis-b** [comment]
Je prévois un créneau pour cela à 11 H
 https://visio.sambaedu.org/b/lau-v67-gj9
A demain

**Comment by ThibautTrarbach** [comment]
A demain
