### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by LeGmask** [Litarvan/pronote-api#33]
Currently we can't use your code for other project, there isn't any licence so it's a big problem for any one would like to use it in official project 👎.

**Comment by StoneSet** [comment]
Je t’avourais que sur un projet de ce type, la licence on s'en fou un peu erm et dit toi que Litarvan ne supporte plus ce projet, il est en deprecated depuis un moment

**Comment by LeGmask** [comment]
ah rip, bah je vais fork et balancer une licence dans un fork

**Comment by LeGmask** [comment]
Since there a licence this issue is useless
