### ISSUE TITLE
Unknown CAS 'ac-nancy-metz

### ISSUE THREAD

**Issue by Jerryh2-0** [Litarvan/pronote-api#37]
Il y a une erreur lors de l'authentification : "Unknown CAS 'ac-nancy-metz". De plus, dans votre code, jai lu que vous vous connectiez à pronote en utilisant kdecole, hors, nous nous connectons (peut-être pas tous les lycées) avec téléservices ([https://teleservices.ac-nancy-metz.fr/](https://teleservices.ac-nancy-metz.fr/)). L'erreur est peut-être due à cela, peut-être pas.

**Comment by trmaud** [comment]
Hello,

kdecole est ce qui sert a décoder le module ATEN (Téléservice).
Le problème sont pas sur l'api mais sur les infrastructure réseaux.
Il y a un appareil de protection de marque F5 network. Qui bloque toute les tentative de passage de l'api. 
Peux être qu'un jours on trouveras.

**Comment by Jerryh2-0** [comment]
Je suppose que c'est mort alors ?

**Comment by Litarvan** [comment]
Avec la rentrée et la v2, tu peux réssayer on sait jamais

**Comment by Jerryh2-0** [comment]
J'ai laissé tombé déjà, je vais fermer ce sujet
