### ISSUE TITLE
Académie de Bordeaux

### ISSUE THREAD

**Issue by dakokonutboi** [Litarvan/pronote-api#42]
L’académie de Bordeaux n'est pas compatible.

**Comment by trmaud** [comment]
Hello,

Elle est pas indiqué comme compatible non ?

**Comment by dakokonutboi** [comment]
Oui justement.
Pardon si mon message était court et pas assez clair, je demande justement si il est prévu qu'elle le devienne.

**Comment by trmaud** [comment]
C'est pas prévu de mon cotée,

Mais tu peux la faire de ton coter et après la pousser dans l'api.
Sa doit être faisable si tu connais un petit peux le js.

Cdt
Thibaut

**Comment by dakokonutboi** [comment]
Tous mes projets récents sont en JS, donc oui.
C'est plutôt le fonctionnement de l'api que je ne connais pas. (Pour être tout a fait honnête je n'ai pas pris le temps de regarder le code.) 
Est-ce que tu pourrais me donner une idée du fonctionnement?

**Comment by trmaud** [comment]
De souvenir, l'académies est un peux plus compliqué que d'habitude.
Car tu doit te connecter sur ce site : [ATEN](https://bv.ac-bordeaux.fr/login/ct_logon_vk.jsp?CT_ORIG_URL=http%3A%2F%2Fbv.ac-bordeaux.fr%2Fsso%2FSSO%3FSPEntityID%3Dhttps%253A%252F%252Fmon.lyceeconnecte.fr%252Fauth%252Fsaml%252Fmetadata%252Fidp.xml)
Mais après il s'authentifie sur cette autre site : [ENT](https://mon.lyceeconnecte.fr/auth/login).

Les deux ont des exemples dans le dossier CAS : 
le ac-lille est l'exemple d'un aten.
et le iledefrance est l'exemple de l'ENT.
Si tu arrive a faire en sorte que l'authentification passe entre les 2 alors tu auras presque gagner.

il te restera a get l'username et le DOM.

Cdt
Thibaut

**Comment by dakokonutboi** [comment]
Tu penses que je pourrais faire ça en Web Scraping avec Puppeteer?
Du style simuler un navigateur, entrer les identifiants, le laisser se connecter puis lire les infos de la page et les rendre avec l'API?

**Comment by trmaud** [comment]
La je serait pas capable de te répondre, seul @Litarvan pourras te dire ce que l'api veux bien. Mais normalement c'est l'api qui qui get tout les info, elle a juste besoin de la page et session pronote.

Cdt
Thibaut

**Comment by dakokonutboi** [comment]
J'ai réussi !
![image](https://user-images.githubusercontent.com/48127169/83973834-dfda7c80-a8e0-11ea-9f66-10314152d029.png)
Finalement j'ai juste refait l'API.
J'ai utilise expressjs et puppeteerjs.
Je vais rendre la source publique des que j'aurai une version qui fonctionne parfaitement.

**Comment by trmaud** [comment]
Donc tu a pas crée un cas pour d'autre personne ?

Cdt
Thibaut

**Comment by dakokonutboi** [comment]
Non non. 
J’ai complètement refait l’api. 
Et là c’est compatible avec n’importe quelle académie. 
(Le code est aussi beaucoup plus court et dans un seul fichier server.js)

**Comment by trmaud** [comment]
Yes, mais a ce que je vois tu récupère strictement rien par rapport a cette api.

et je suis pas sur que sa fonctionne sur n'importe quel académies, car tu a vu un system est non les 5 déjà répertorier.

A voir ce que sa donne quand tu partagera.

cdt
Thibaut
