### ISSUE TITLE
Fix error handling

### ISSUE THREAD

**Issue by ccgauche** [Litarvan/pronote-api#46]
Connection errors are not correctly handled in "Ile de France". Indeed, if the password is incorrect the error `Unknown` CAS is raised.
Furthermore, errors are not in a correct JSON format:
```json
{
"error": ""Unknown CAS""
}
```
Should should remove one `"` from each side.

**Comment by Litarvan** [comment]
La gestion des erreurs a été refaite proprement dans la v2
