### ISSUE TITLE
Modifier des données ?

### ISSUE THREAD

**Issue by petittitouan** [Litarvan/pronote-api#47]
Bonjour, avec cette API, je suis en train de développer un Logiciel qui récupère les devoirs régulièrement afin d'envoyer des notifications dès l'apparition d'un nouveau devoir.

J'aimerais cependant pouvoir Valider des devoirs (et encore mieux Uploader des fichiers).

**Comment by 23Felons23** [comment]
Oui ça serais incroyable d'ajouter l'upload des fichiers et de tout ce qui entoure les devoirs !

**Comment by petittitouan** [comment]
Pourquoi ? @ThibautTrarbach

**Comment by ThibautTrarbach** [comment]
Il faut lire le readme. Il n'y a plus d'api et donc plus d'aide et débug dessus

**Comment by tieb62** [comment]
J'ai vu c'est pour cela que j'ai supprimé mon commentaire
