### ISSUE TITLE
Tous les devoirs ne sont pas retournés

### ISSUE THREAD

**Issue by JBX028** [Litarvan/pronote-api#48]
Bonjour,

Premièrement merci pour cette librairie très utile. J'ai réussi à me connecter mais quand je regarde l'output et plus précisément la partie "homework", je ne vois que 5 sections pour les devoirs alors que lorsque je regarde pronote, il y a beaucoup plus de devoirs (fait ou non).
Avez-vous une idée ? Je dois avouer ne pas avoir regarder le fichier pronote.js pour voir si un critère de date ou autre est la raison de mon problème.

Merci :)

**Comment by Litarvan** [comment]
Ca ne retourne que les devoirs des deux dernières semaines (dont l'actuelle)

**Comment by JBX028** [comment]
Bonjour,
Merci pour votre réponse mais en comparant de plus près les 3 (et pas 5) devoirs qui sont retournés sont d'octobre et novembre 2019 et depuis il y a eu beaucoup d'autres devoirs. Je ne vois rien de spécial pour ces 3 devoirs qui pourrait expliquer pourquoi cela sont retournés et non les autres.
Je ne vois pas de paramètres en entré pour définir une période....

**Comment by Litarvan** [comment]
Réglé dans la v2, il est possible de bien plus facilement selectionner les devoirs voulus

**Comment by JBX028** [comment]
Merci beaucoup. Dès que le serveur pronote de ma fille sera à nouveau disponible à la rentrée je vais essayer.
