### ISSUE TITLE
Error when Fetching information ( TypeError: Cannot read property 'V' of undefined ) 

### ISSUE THREAD

**Issue by coco33920** [Litarvan/pronote-api#6]
Hi, i just tested your API and i made a request like the template in "README.md" :+1: 
According to 

`Logging in 'thomas4' for 'https://0330028b.index-education.net/pronote/' using regular login
Logged in 'thomas4'
Successfully logged user 'thomas4' in 4.108s`
The connection worked.

Request : 
`{
  "type": "fetch",
  "username": "thomas4",
  "password": "PASSWORD",
  "url": "https://0330028b.index-education.net/pronote/"
}`
Error 
`TypeError: Cannot read property 'V' of undefined
    at result.absences.push.absences.absences.donnees.listeAbsences.V.map.absence (/home/charlotte/Téléchargements/pronote-api-master/src/pronote.js:404:56)
    at Array.map (<anonymous>)
    at Object.fetch (/home/charlotte/Téléchargements/pronote-api-master/src/pronote.js:403:56)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`
I used Postman to call the API, I run the API on local on my computer on a fresh install of node ( Ubuntu 18.04 64 bit, kernel 5.0.0-37 )
I will test with another account if i can find a friend.
Sorry, i'm not very familiar with JS/node.
Charlotte.

**Comment by Litarvan** [comment]
This has just been fixed on master, can you try ?

**Comment by coco33920** [comment]
Yep that's work ! 
Thanks :)
Charlotte.
