### ISSUE TITLE
Erreur lors du retour de l'EDT sur le serveur GraphQL

### ISSUE THREAD

**Issue by Firokat** [Litarvan/pronote-api#68]
Je suis en train de découvrir votre superbe API mais un problème survient 

En souhaitant recevoir l'EDT avec la query
```
{
    timetable(from: "2020-09-01") {
        room   
    }
}
```
le serveur renvoie 

```
{
    "data": {
        "timetable": [
            {
                "room": null
            },
            {
                "room": null
            },
            {
                "room": null
            },
            {
                "room": null
            },
            {
                "room": null
            }
        ]
    }
}
```
mais avec le bon nombre de cours

PS : J'utilise le site de démo

**Comment by Litarvan** [comment]
Effectivement, j'avais testé tout mais pas ça et forcément x)
C'est réglé, push, et release, tu peux mettre à jour en 2.0.1 !
