### ISSUE TITLE
Erreur 404 lors de l'usage du CAS "hdf"

### ISSUE THREAD

**Issue by luzzardik** [Litarvan/pronote-api#72]
Hello!
Lors de l'usage du cas "hdf", la bibliothèque essaye quand même d'appeler `POST /auth/login` (qui retourne un 404 en cas d'usage d'un CAS).

Je me demande si c'est pas lié au fait que mes accès sont bloqués. (j'utilise pour la première fois l'API pour monitorer Pronote, donc j'appelle toutes les 15 secondes).

Je vérifierai lorsque mes accès seront rétablis si c'est seulement un problème permissif quand même !

**Comment by Litarvan** [comment]
Qu'est-ce que tu appelles POST /auth/login ? Je peux voir l'erreur que tu obtiens ?

**Comment by bugsounet** [comment]
bonsoir, une erreur plus ou moins equivalente avec le cas "hdf"

voici la config:
```
const url = "https://0590083v.index-education.net/pronote/";
const username = 'mon login';
const password = 'mon passwd';
const cas = "hdf"
```

recherche un login sur `https://0590083v.index-education.net/pronote/auth/login` mais n'existe pas (erreur 404)
j'ai essayer mes identifiants sur ` https://enthdf.fr/auth/login` cela fonctionne correctement

une idée ou besoin de plus d'information ?

merci de votre aide

**Comment by Litarvan** [comment]
Salut, j'avais effectivement fait une grosse erreur dans l'implémentation d'openent, tu peux essayer d'extraire le contenu de https://github.com/Litarvan/pronote-api/archive/master.zip dans node_modules/pronote-api/ et me dire si ton problème est changé ?

**Comment by bugsounet** [comment]
```
node test
{ code: 7, message: 'The instance is closed, try again later' }
```
il y a du mieux :)

je regarde plus en profondeur ce soir, je suis en plein codage aussi !

**Comment by Litarvan** [comment]
Ça c'est que le CAS marche, mais que Pronote est fermé (je pense que tu as toi même ce message en allant sur Pronote avec ton navigateur), issue résolue donc

**Comment by bugsounet** [comment]
oui j'ai verifier.
Par contre, peux tu faire une liste des CAS dispo sur le Readme ?
j'ai eu du mal a trouver (lecture du code, et recherche dans le repo)
cela m'aiderai dans mon Projet ;)

Le projet serai d'afficher les informations de Pronote sur un mirroir connecté,
pour la partie configuration cela aiderai beaucoup :)

**Comment by Litarvan** [comment]
Très bonne idée ! C'est fait :)

**Comment by Litarvan** [comment]
D'ailleurs j'ai release la 2.1.3 avec le fix !

**Comment by bugsounet** [comment]
Merci ;)
