### ISSUE TITLE
Teacher support

### ISSUE THREAD

**Issue by papey** [Litarvan/pronote-api#75]
Hi, 

I really need teacher support on this lib, do you need help ? What needs to be done ?

Thanks for this work !

**Comment by Litarvan** [comment]
Accounts types other than students are our current focus right now :)

**Comment by papey** [comment]
Ok cool. Ask if needed for reviews, feedback, whatever.

**Comment by Litarvan** [comment]
Hello again ! The teacher panel has a lot of features, I would need to know what do you need to be implemented ?

**Comment by papey** [comment]
I mainly need to work with time schedules from both a teacher account and all the classrooms (to find the free ones etc). Thanks again !

**Comment by Bastiendsp** [comment]
Hi, I need also to access to teacher side... But I want to mark an absence or presence..
Is it possible to check if you can add it to the api? 
Thanks you very much! @Litarvan @ThibautTrarbach
