### ISSUE TITLE
TypeError: Cannot read property 'urlSiteIndexEducation' of undefined

### ISSUE THREAD

**Issue by Niromash** [Litarvan/pronote-api#76]
Salut, j'ai eu un soucis quand j'ai voulu me connecter via pronote-api en utilisant le CAS Orléans-Tours.
https://i.nmsh.tk/9Bf4tN
J'ai fais un console.log de params dans le fichier de l'erreur et je vois pas 'General' dans l'object.

Mise à part ça, le fait qu'on soit plus dépendant d'une partie serveur et client est une bonne idée 👍

**Comment by Litarvan** [comment]
Salut ! Je pourrais voir à quoi ressemble ce params et avoir l'URL de ton serveur pronote ? (Si ça te dérange, en privé sur Discord Litarvan#0420 )

**Comment by Litarvan** [comment]
Réglé via Discord, la 2.1.3 est sortie et règle le problème :)

**Comment by jadou7** [comment]
REOPEN:
J'ai le meme souci de "TypeError: Cannot read property 'urlSiteIndexEducation' of undefined" qui revient
