### ISSUE TITLE
ajouter le languedoc roussillon ?

### ISSUE THREAD

**Issue by Syf-dev** [Litarvan/pronote-api#77]
es possible d'ajouter l'occitanie pour pronote

**Comment by Litarvan** [comment]
Salut ! Ce n'est ni le CAS ac-toulouse ni ac-montpellier ? Si oui je peux avoir le lien du CAS ?

**Comment by Syf-dev** [comment]
> Salut ! Ce n'est ni le CAS ac-toulouse ni ac-montpellier ? Si oui je peux avoir le lien du CAS ?

C'est celui de Montpellier my bad

**Comment by Litarvan** [comment]
Le CAS est déjà intégré depuis longtemps et s'appelle `ac-montpellier`

Je ferme l'issue du coup, dis moi si tu as un problème avec
