### ISSUE TITLE
Devoirs ne sont pas retournés

### ISSUE THREAD

**Issue by JBX028** [Litarvan/pronote-api#80]
Bonjour,

Je ne vois pas les devoirs retournés dans l'objet session ni dans session.homeworks() alors qu'il y en a dans https://demo.index-education.net/

Faut-il faire quelque chose de spécial pour obtenir les devoirs?

**Comment by trmaud** [comment]
Hello, Les devoirs sont bien retournée, 
Il suffit de donné la date de depars et la date de fin : 
![image](https://user-images.githubusercontent.com/30575266/92766383-7746e400-f396-11ea-895e-e6634439d956.png)

Comme tu peux le voir ici :  
https://github.com/Litarvan/pronote-api/blob/88bf3195b469e630064f24f669398a1ce4f93eb1/bin/fetch.js#L34

Cdt
Thibaut

**Comment by Litarvan** [comment]
J'aimerais rajouter aussi qu'il faut bien indiquer l'heure dans la date, parce que sinon ça définit minuit, donc ça risque de te poser problème. Ca et ce que Thibaut a dit était précisé dans la documentation de la fonction d'ailleurs :)

**Comment by JBX028** [comment]
Bonjour,
Oui en effet j'aurais du regarder le code et à présent j'arrive à retourner les devoirs mais est-ce que la remarque sur l'heure est la raison pour laquelle il y a un décalage avec la date des devoirs sur le site et ce qui apparaît dans l'output ([x].for)
Par exemple, sur le site il y a un devoir de math pour le 24 sept mais dans l'output il y a "for": "2020-09-**23**T22:00:00.000Z", et c'est pareil pour tous les devoirs et le même décalage existe avec la date à laquelle le devoir a été donné.

**Comment by Litarvan** [comment]
La date que tu vois est en UTC, c'est à dire sans décalage horaire, donc -2h par rapport à la France, d'où le fait que l'heure soit calée sur 22h, car +2 ça fait bien 2020-09-24 à 00h. Normalement tout langage correct devrait pouvoir lire ça en comptant le décalage.

**Comment by JBX028** [comment]
ok merci
