### ISSUE TITLE
Probleme CAS Bordeaux

### ISSUE THREAD

**Issue by zaienj** [Litarvan/pronote-api#81]
Bonjour j'ai un petit problème qui vient peut etre de moi mais mon lycée on eu la bonne idée d'utiliser le cas de ma region ( ac de bordeaux ) donc j'essaye en donnant l'url qui redirige vers le pronote mais ça marche pas si on peut m'aider je prends

**Comment by trmaud** [comment]
Un peux plus d'info serait utile, tu a mis quel url.
Tu utilise l'api en direct ou alors tu passe par le serveur graphQL ?

Cdt
Thibaut

**Comment by zaienj** [comment]
Merci de ta réponse dsl si mais info sont vague je débute dans node js
donc je me co avec cette url:
https://0332722e.index-education.net/pronote/eleve.html
qui me redirige vers le cas de ma region pour le cas j'ai mis ça:
`const cas = 'ac-bordeaux';`
je sais pas si j'ai fait une connerie sur cette ligne et graphQL je sais pas trop j'ai mis les commande donner mais sans plus

**Comment by Litarvan** [comment]
Salut, on va difficilement pouvoir t'aider si tu ne nous dis pas l'erreur que tu rencontres haha

**Comment by zaienj** [comment]
bah je rencontre l'erreur mauvaise identifiant alors que ce sont les bon ( j'arrive avoir ce résultat sans utilise le cas et en le mettant j'ai `{ code: 1,
  message: 'Unknown CAS \'ac-bordeaux\' (use \'none\' for no CAS)' }
`
donc je sais pas si c le nom du cas ou autre
je précise que mais identifiants sont les bon
( et le prb c que si j'essaye trop de fois ça me bloque et c reloue)

**Comment by trmaud** [comment]
Salut,
Peux tu me donner le site sur le quel tu te connectes.

Cdt
Thibaut

**Comment by zaienj** [comment]
le site est celui si https://0332722e.index-education.net/pronote/eleve.html
et ça nous redirige sur l'iterface de lycée connecter pour nous logger

**Comment by trmaud** [comment]
Donc tu te connect sur ce site ?

Cdt
Thibaut

**Comment by zaienj** [comment]
oui c ça

**Comment by trmaud** [comment]
Cela est simple, l'academie de bordeaux n'utilise pas se site, je te prepare un cas avec celui ci

**Comment by trmaud** [comment]
Hello,
Voila, je viens de te l'ajouter le :
https://github.com/Litarvan/pronote-api/commit/7cfd15f5dd52bf847ea53ae21dbb9460c338c8eb#diff-0660bec9b8522ba02f91744e89c5a83f

**Comment by zaienj** [comment]
ah c bizarre car mon lycée nous on dit que c’était pour la région donc je me suis dit que l'ac de bordeaux c'etait l'ac de bordeaux 

merci de ton en tout cas, c cool d'avoir de l'aide comme ça

donc du coups je mais a jour pronote api et je mais dans le cas lycée connecter ou je modif directe sur mon pc ??

et par hasard comment ta fait pour faire ça ??

**Comment by trmaud** [comment]
Elle est pas encore en npm, tu a juste a download mon edit et a le placer au même endroit chez toi.

**Comment by zaienj** [comment]
ok dac mrc de ton aide

**Comment by trmaud** [comment]
Derien
