### ISSUE TITLE
CAS: hdf Erreur

### ISSUE THREAD

**Issue by bugsounet** [Litarvan/pronote-api#83]
Salut,

la derniere fois tu avais mis a jour le CAS: `hdf`,
je ne pouvais pas réellement me logué ... effectivement le site était en maintenance (un peu trop souvent d'ailleur...)

actuellement, il est `debout?` mais j'ai cette erreur, je me permet de t'en faire part: 
```
TypeError: Cannot destructure property `N` of 'undefined' or 'null'.
    at fromPronote (/home/bugs/MagicMirror/node_modules/pronote-api/src/data/objects.js:1:21)
    at getUser (/home/bugs/MagicMirror/node_modules/pronote-api/src/fetch/pronote/user.js:25:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

peux être un bug ou un oubli de a part ? (lol ... ça m'arrive aussi, je te rassure !)

**Comment by Litarvan** [comment]
Salut, je prédis que tu utilises un compte parent, ai-je raison :D ?

**Comment by bugsounet** [comment]
ah ouai.... comme une con, je suis entrain de logué ton user.js pour debug... pfff bravo !

**Comment by Litarvan** [comment]
Le support des autres types de comptes est actuellement en cours. Pour l'instant j'ai déjà un support parent complètement terminé, simplement c'est sur la branche `litarvan/accounts`, utilise cette branche et tout devrait marcher :)

**Comment by bugsounet** [comment]
je vais le git clone pour voir, merci de l'info :)
