### ISSUE TITLE
Prb Lycée connecter 

### ISSUE THREAD

**Issue by zaienj** [Litarvan/pronote-api#85]
Re Bonjour,
Dsl si je spam mais j'ai encore une erreur.
voici le code de l'erreur 
`{ Error: Cannot find module './generics/openent'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/julien/node_modules/pronote-api/src/cas/lyceeconnecte.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
`
je ne comprend toujours pas si c moi l'erreur ou si ça vienne de lycée connecter

**Comment by trmaud** [comment]
Hello,
Possible de voir ta requette avec le user et passwrd de cacher ?
Ainsi que l'emplacement du fichier que tu a ajouter a ton api ?

Cdt
Thibaut

**Comment by zaienj** [comment]
voici le code que j'ai mis je pense que tu parle de ça
`const pronote = require('pronote-api');

// Exemple
const url = 'https://0332722e.index-education.net/pronote/eleve.html';
const username = '***';
const password = '***';
const cas = 'lyceeconnecte';

async function main()
{
    const session = await pronote.login(url, username, password, cas);

    console.log(session.user.name); // Affiche le nom de l'élève
    console.log(session.user.studentClass.name); // Affiche la classe de l'élève

    const timetable = await session.timetable(); // Récupérer l'emploi du temps d'aujourd'hui
    const marks = await session.marks(); // Récupérer les notes du trimestre

    console.log(`L'élève a ${timetable.length} cours aujourd'hui`);
    console.log(`et a pour l'instant une moyenne de ${marks.averages.student} ce trimestre.`);

    // etc. les fonctions utilisables sont 'timetable', 'marks', 'contents', 'evaluations', 'absences',
    // 'infos', et 'menu', sans oublier les champs 'user' et 'params' qui regorgent d'informations.
}

main().catch(err => {
    if (err.code === pronote.errors.WRONG_CREDENTIALS.code) {
        console.error('Mauvais identifiants');
    } else {
        console.error(err);
    }
});

et le lien du fichier c ce lui ci 
`/home/julien/node_modules/pronote-api/src/cas/lyceeconnecte.js`
voila voila j'esper que c ça

**Comment by trmaud** [comment]
Oups erreur de ma part, j'ai oubliée d'edit un fichier.
Voila c'est fait, tu a normalement juste a faire la même modification.

Cdt
Thibaut

**Comment by zaienj** [comment]
Il y a maintenant une nouvelle erreur 
`TypeError: Cannot read property 'urlSiteIndexEducation' of undefined
    at getParams (/home/julien/node_modules/pronote-api/src/fetch/pronote/params.js:28:46)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by jadou7** [comment]
`TypeError: Cannot read property 'urlSiteIndexEducation' of undefined` Ce probleme avait déjà été réglé mais revient apparemment

**Comment by Litarvan** [comment]
Hello, j'ai essayé de régler ça en despi, dites moi si ça marche sur master

**Comment by zaienj** [comment]
`L'élève a 1 cours aujourd'hui
et a pour l'instant une moyenne de undefined ce trimestre.`
ça marche trop cool merci je vais m'amuser avec l'api maintenant
