### ISSUE TITLE
Cas qui ne fonctionne pas

### ISSUE THREAD

**Issue by Darukity** [Litarvan/pronote-api#88]
**Bonjours ou bonsoir, voici mon problème quand je met 'none' dans le cas je reçois l'erreur ci dessous :** 

{ code: 1,
  message: 'Unknown CAS \'none\' (use \'none\' for no CAS)' }

**et le code :** 
const pronote = require('pronote-api');

// Exemple
const url = '';
const username = '';
const password = '';
const cas = 'none';

async function main()
{
    const session = await pronote.login(url, username, password, cas);
    
    console.log(session.user.name); // Affiche le nom de l'élève
    console.log(session.user.studentClass.name); // Affiche la classe de l'élève
    
    const timetable = await session.timetable(); // Récupérer l'emploi du temps d'aujourd'hui
    const marks = await session.marks(); // Récupérer les notes du trimestre
    
    console.log(`L'élève a ${timetable.length} cours aujourd'hui`); 
    console.log(`et a pour l'instant une moyenne de ${marks.averages.student} ce trimestre.`);
    
    // etc. les fonctions utilisables sont 'timetable', 'marks', 'contents', 'evaluations', 'absences',
    // 'infos', et 'menu', sans oublier les champs 'user' et 'params' qui regorgent d'informations.
}

main().catch(err => {
    if (err.code === pronote.errors.WRONG_CREDENTIALS.code) {
        console.error('Mauvais identifiants');    
    } else {
        console.error(err);
    }
});

**_Notez qu'il y a normalement les bonnes information dans const url, const username et const password (je les ai enlever pour ne pas révéler ma position)._**

**Comment by Litarvan** [comment]
Salut, ce bug a normalement été réglé dans sur master, essaie d'utiliser l'API en remplaçant le contenu de `node_modules/pronote-api/` par le contenu de ce zip https://github.com/Litarvan/pronote-api/archive/master.zip

**Comment by Darukity** [comment]
Merci mais maintenant ça me met cette erreur:

```
pronote\node_modules\webidl-conversions\lib\index.js:357
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (pronote\node_modules\whatwg-url\dist\URL.js:3:21)
```

**Comment by Litarvan** [comment]
Salut, ta version de Node.JS est beaucoup trop ancienne, essaie d'utiliser au moins la version 10

**Comment by Darukity** [comment]
ok, merci
