### ISSUE TITLE
CAS qui ne fonctionne pas

### ISSUE THREAD

**Issue by jadou7** [Litarvan/pronote-api#89]
Probleme de CAS avec ac-grenoble
J'utilise [ce commit](https://github.com/Litarvan/pronote-api/commit/0e889bbe9612a23f5f1950a29d0a4f8c44f040e4) directement dans mon node_modules et voici l'erreur:

`TypeError: Cannot read property 'urlSiteIndexEducation' of undefined
    at getParams (c:\Users\Jadou\Desktop\Projets Pronote\PronoteBot\node_modules\pronote-api\src\fetch\pronote\params.js:28:46)
    at processTicksAndRejections (<node_internals>/internal/process/task_queues.js:97:5)
    at async Object.login (c:\Users\Jadou\Desktop\Projets Pronote\PronoteBot\node_modules\pronote-api\src\auth.js:29:22)
    at async main (c:\Users\Jadou\Desktop\Projets Pronote\PronoteBot\commands\pronote\menu.js:41:29) {stack: 'TypeError: Cannot read property 'urlSiteIndex…te\PronoteBot\commands\pronote\menu.js:41:29)', message: 'Cannot read property 'urlSiteIndexEducation' of undefined'}`

**Comment by Litarvan** [comment]
Salut ! J'ai push un fix, tu peux me dire si ça marche ?

**Comment by jadou7** [comment]
`code:undefined
message:'Only 8, 16, 24, or 32 bits supported: undefined'
stack:'Error: Only 8, 16, 24, or 32 bits supported: undefined\n    at _checkBitsParam (c:\\Users\\Jadou\\Desktop\\Projets Pronote\\PronoteBot\\node_modules\\node-forge\\lib\\util.js:137:11)\n    at ByteStringBuffer.util.ByteStringBuffer.putInt (c:\\Users\\Jadou\\Desktop\\Projets Pronote\\PronoteBot\\node_modules\\node-forge\\lib\\util.js:381:3)\n    at decipher (c:\\Users\\Jadou\\Desktop\\Projets Pronote\\PronoteBot\\node_modules\\pronote-api\\src\\cipher.js:55:20)\n    at auth (c:\\Users\\Jadou\\Desktop\\Projets Pronote\\PronoteBot\\node_modules\\pronote-api\\src\\auth.js:80:22)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async Object.login (c:\\Users\\Jadou\\Desktop\\Projets Pronote\\PronoteBot\\node_modules\\pronote-api\\src\\auth.js:33:9)\n    at async main (c:\\Users\\Jadou\\Desktop\\Projets Pronote\\PronoteBot\\commands\\pronote\\menu.js:32:29)'
`
Nouvelle erreur, désolé mais je ne voit pas du tout d'où cela peut venir.

**Comment by Litarvan** [comment]
Oula, ça devient bizarre, tu crois pouvoir me contacter sur Discord à Litarvan#0420 ?

**Comment by Litarvan** [comment]
Réglé sur Discord, node-forge n'était pas à la bonne version dû à un bug d'NPM.

**Comment by jadou7** [comment]
Réglé sur discord: probleme de node-forge qui n'était pas dans la bonne version (0.7.4 pour mon cas alors que ca devrait etre 0.6.33)
