### ISSUE TITLE
Ajout d'une fonction geo()

### ISSUE THREAD

**Issue by Androz2091** [Litarvan/pronote-api#91]
Bonjour, j'aimerai pouvoir obtenir la liste des établissement à proximité (comme sur l'application officielle de Pronote). Le fork de [wow0000](https://github.com/wow0000/pronote-lib) permet déjà ça, et même si je peux moi-même maintenir ma propre fonction dans mon code, ce serait plus simple qu'elle soit intégrée dans ce module. On pourrait créer un fichier `geo.js` et l'exporter, ce serait utile et assez simple.
Je peux me charger de faire une PR, mais je voulais d'abord avoir votre avis sur l'intégration de cette fonctionnalité à la lib

**Comment by Litarvan** [comment]
Ça pourrait effectivement servir, je te laisse le plaisir de faire cette PR :)
