### ISSUE TITLE
Ajout de règles pour les Issues Github

### ISSUE THREAD

**Issue by MonsieurBibo** [Litarvan/pronote-api#92]
Je propose d'ajouter des règles sur les issues GitHub pour améliorer la visibilité et faciliter la vie aux contributeurs. Il existe de nombreuses templates. 

Voici un exemple: https://github.com/stevemao/github-issue-templates/blob/master/bugs-only/ISSUE_TEMPLATE.md

**Comment by Litarvan** [comment]
Honnêtement vu les erreurs beaucoup trop bizarres et le fait que certains n'aient pas l'habitude de GitHub (voire du développement en général) j'ai volontairement choisi de ne pas imposer de templates. Ca ne pose pas vraiment de problème jusqu'ici.
