### ISSUE TITLE
GQL: 400 Bad Request

### ISSUE THREAD

**Issue by MAXOUXAX** [Litarvan/pronote-api#93]
Bonjour !

J'ai installé le serveur GQL sur mon serveur en utilisant comme bind-adress `0.0.0.0` (au lieu de `127.0.0.1`) dû aux problèmes de connexion liés à l'utilisation de Pterodactyl (qui utilise des containers Docker, ce qui me rend impossible de me connecter en utilisant l'IP `127.0.0.1` [puisqu'elle référerait au container courant et non pas au serveur] ni en utilisant l'IP de l'interface réseau de Pterodactyl [puisque le serveur est bind sur `127.0.0.1` par défaut]).
Le serveur se lance bien, je peux y accéder correctement via mon navigateur, mais lorsque j'effectue une requête sur l'endpoint `/auth/login` en utilisant Jsoup, j'obtiens une erreur 400 Bad Request.

Je n'ai aucune information supplémentaire puisqu'aucun log n'est présent mis à part le "Listening on 0.0.0.0:21727" lors du lancement du serveur GQL, que faire ?

**Comment by Litarvan** [comment]
Normalement dans la requête qui t'envoie un 400 tu auras une réponse avec ce qui ne va pas.
Mais c'est soit un header `Content-Type: application/json` manquant, soit le JSON en corps de la requête qui a une erreur de syntaxe, soit un champ manquant dans le JSON.

**Comment by Litarvan** [comment]
Au passage, ouvrir le serveur sur l'exterieur est pas forcément une superbe idée, essaie de bind le port 21727 du container sur 127.0.0.1:21727 si tu peux

**Comment by MAXOUXAX** [comment]
Au niveau du header Content-Type, je l'ai bien mis, cela dit au niveau du JSON je suis pas certain que j'ai fais les choses correctement, j'ai jamais vraiment utilisé Jsoup et j'ai pas forcément regardé de documentation autre que la javadoc directement, du coup voici mon code:

```java
Connection connection = Jsoup.connect(pronoteServerUrl+"/auth/login");
connection.header("Content-Type", "application/json");
connection.data("url", configurationManager.getStringValue("pronote_url"));
connection.data("username", configurationManager.getStringValue("pronote_username"));
connection.data("password", configurationManager.getStringValue("pronote_password"));
connection.data("cas", configurationManager.getStringValue("pronote_cas"));
try{
    Document document = connection.post();
    String token = document.attr("token");
    System.out.println("token = " + token);
}catch (ConnectException e){
    System.out.println("Une erreur est survenue lors de la connexion !");
    e.printStackTrace();
}
```

J'ai déjà vérifié et toutes les données que j'injecte sont valides, donc pas de problème à ce niveau là.
Et pour le coup j'ai un peu mal expliqué, mais le serveur GQL est hébergé classiquement sur mon serveur et pas dans un container Docker, c'est mon application Java qui est dans un container Docker et qui peut pas se connecter au serveur GQL en utilisant une autre IP que celle de l'interface Pterodactyl, sauf que si je bind le serveur sur 127.0.0.1, il considère l'IP de l'interface réseau comme étant extérieur et j'obtiens un "Connection refused", et si je bind le serveur sur l'IP de l'interface réseau Pterodactyl, j'aurai le même problème puisque j'ai déjà des containers Docker sur mon serveur et les IPs peuvent changer ^^

**Comment by Litarvan** [comment]
Je ne connais pas JSoup mais je pense pas que ça soit la bonne manière de faire, essaie d'utiliser une requête Java classique (je vois pas pourquoi t'aurais besoin de JSoup ici) avec un parser json basique comme org.json

Tu peux aussi regarder le contenu de la réponse (malgré le 400) pour voir ce qui ne va pas (ça devrait y être indiqué).

**Comment by MAXOUXAX** [comment]
Sinon [cette repo](https://github.com/Litarvan/pronote-api-client-java) ça fonctionne encore ? 😅

**Comment by Litarvan** [comment]
Non désolé je l'ai pas mis à jour en revanche tu peux regarder comment je fais la requête JSON dedans, c'est là https://github.com/Litarvan/pronote-api-client-java/blob/master/src/main/java/fr/litarvan/pronote/PronoteAPI.java#L103

**Comment by MAXOUXAX** [comment]
Alors du coup j'ai modifié mon code ~~`en faisant un copié collé du tiens`~~ et je viens de tester, j'ai une erreur 500 sur la requête HTTP, et une erreur au niveau du serveur GQL.

~~`Ton`~~ Mon code:
```java
URL url = new URL(pronoteServerUrl+"/auth/login");
HttpURLConnection connection = (HttpURLConnection) url.openConnection();
connection.setDoInput(true);
connection.setDoOutput(true);
connection.setRequestMethod("POST");
connection.setRequestProperty("Content-Type", "application/json");
JSONObject jsonObject = new JSONObject();
jsonObject.put("url", configurationManager.getStringValue("pronote_url"));
jsonObject.put("username", configurationManager.getStringValue("pronote_username"));
jsonObject.put("password", configurationManager.getStringValue("pronote_password"));
jsonObject.put("cas", configurationManager.getStringValue("pronote_cas"));
try (DataOutputStream out = new DataOutputStream(connection.getOutputStream()))
{
    out.write(jsonObject.toString().getBytes(StandardCharsets.UTF_8));
}
StringBuilder content = new StringBuilder();
try (BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream(), StandardCharsets.UTF_8)))
{
    String line;
    while ((line = in.readLine()) != null)
    {
        content.append(line).append(System.lineSeparator());
    }
}
connection.disconnect();
JSONObject finalObject = new JSONObject(content.toString());
System.out.println("finalObject.toString() = " + finalObject.toString());
```

Erreur côté serveur GQL:
```javascript
Error during request handling :
TypeError: Cannot read property 'action' of undefined
     at submitForm (/usr/local/lib/node_modules/pronote-api/src/cas/api.js:8:66)
     at login (/usr/local/lib/node_modules/pronote-api/src/cas/kdecole-wayf.js:19:21)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
     at async getStart (/usr/local/lib/node_modules/pronote-api/src/auth.js:71:12)
     at async Object.login (/usr/local/lib/node_modules/pronote-api/src/auth.js:17:19)
     at async login (/usr/local/lib/node_modules/pronote-api/src/server/auth.js:17:23)
```

**Comment by Litarvan** [comment]
Tu as mis quoi en CAS et en URL ? Si tu ne veux pas le divulguer, envoi moi ça en privé sur Discord : Litarvan#0420

**Comment by MAXOUXAX** [comment]
Au niveau du CAS c'est `ac-nancy-metz` et l'URL c'est l'URL du serveur Pronote, c'est pas un FQDN mais une IP ainsi qu'un port et un chemin juste après (donc genre `184.426.32.185:8088/pronote`) ^^
(Sinon je t'ai add sur Discord si tu veux l'IP exacte xD)

**Comment by trmaud** [comment]
Hello,
Tu a trouver ta solution ou tu a encore un problèmes ?

Cdt
Thibaut

**Comment by MAXOUXAX** [comment]
Hello, j'ai envoyé l'URL à Litarvan sur Discord et j'attends une réponse :)

**Comment by trmaud** [comment]
Hello,
Ok je sait que @Litarvan viens de faire sa rentrée, il est donc un peux surcharger. Je te laisse me contacter par discord pour voir si je peux pas te dépanner.
Discord : Thibaut Black#0001
Cdt
Thibaut

**Comment by MAXOUXAX** [comment]
Problème réglé, merci à @trmaud 👍 
(Pour les curieux, le problème était que j'avais mal formé l'URL du serveur Pronote, en oubliant le protocole (http://) devant l'URL xD)
