### ISSUE TITLE
Problème avec la property 'endwith'

### ISSUE THREAD

**Issue by THEMIODEV** [Litarvan/pronote-api#98]
Bonjour:

J'ai tenté d’exécuter le script d'exemple avec quelques modifications

```
require('dotenv').config({ path: 'dotenv' });

const pronote = require('pronote-api');

const url = process.env.pronoteurl;
const username = process.env.pronoteid;
const password = process.env.pronotepassword;

async function main()
{
    const session = await pronote.login(url, username, password/*, cas*/);
    
    console.log(session.user.name); // Affiche le nom de l'élève
    console.log(session.user.studentClass.name); // Affiche la classe de l'élève
    
    const timetable = await session.timetable(); // Récupérer l'emploi du temps d'aujourd'hui
    const marks = await session.marks(); // Récupérer les notes du trimestre
    
    console.log(`L'élève a ${timetable.length} cours aujourd'hui`); 
    console.log(`et a pour l'instant une moyenne de ${marks.averages.student} ce trimestre.`);
    
    // etc. les fonctions utilisables sont 'timetable', 'marks', 'contents', 'evaluations', 'absences',
    // 'infos', et 'menu', sans oublier les champs 'user' et 'params' qui regorgent d'informations.
}

main().catch(err => {
    if (err.code === pronote.errors.WRONG_CREDENTIALS.code) {
        console.error('Mauvais identifiants');    
    } else {
        console.error(err);
    }
});
```

Sauf que j'ai un message d'erreur qui apparaît soudainement qui provient du fichier "/src/auth.js" avec une erreur par rapport à la property 'endsWith'

`TypeError: Cannot read property 'endsWith' of undefined
    at getServer (C:\Users\enzoz\Desktop\Apps\Dev\themio-pronote\node_modules\pronote-api\src\auth.js:44:13)
    at Object.login (C:\Users\enzoz\Desktop\Apps\Dev\themio-pronote\node_modules\pronote-api\src\auth.js:16:20)
    at main (C:\Users\enzoz\Desktop\Apps\Dev\themio-pronote\index.js:11:35)
    at Object.<anonymous> (C:\Users\enzoz\Desktop\Apps\Dev\themio-pronote\index.js:26:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47`

Je sais pas si vous avez une idée :/ 

EDIT: J'ai l'impression que ce n'est pas compatible avec dotenv 🤔

**Comment by trmaud** [comment]
Hello,

Alors en premier vérifie tes info avec le fichier de base.
Et si tu veux utiliser env, je te conseil de te faire un petit programme et d'instaler la lib avec NPM

Cdt
Thibaut

**Comment by THEMIODEV** [comment]
Bonsoir,

Du coup, j'ai réussi à me connecter, tout marche correctement (sans le dotenv).
J'ai une autre question: Comme afficher le nombre et / ou les heures d'absences?

Car j'ai ajouté ${session.absences()} mais le reste des parenthèses, je suis complètement perdu.

**Comment by Litarvan** [comment]
Regarde les types pour voir la liste des champs disponibles :)
