### ISSUE TITLE
Liste des devoirs et gestion multi élèves

### ISSUE THREAD

**Issue by JBX028** [Litarvan/pronote-api#99]
Bonjour,

Je réouvre une issue car j'ai toujours un problème avec la récupération des devoirs. Dans l'output suivant il y a un devoir donné le 15 pour le 22 (avec éventuellement un décalage : UTC vs CET) mais lorsque je regarde la démo, il y a bien un devoir mais le **contenu est different**:

  
{
        "description": "**Choisir un artiste du courant impressionniste et rechercher sa biographie et ses oeuvres célèbres**",
        "htmlDescription": "<div>Choisir un artiste du courant impressionniste et rechercher sa biographie et ses oeuvres célèbres</div>",
        "subject": "ARTS PLASTIQUES",
        "givenAt": "2020-09-15T22:00:00.000Z",
        "for": "2020-09-22T22:00:00.000Z",
        "done": false,
        "color": "#173ED9",
        "files": []
 }

![image](https://user-images.githubusercontent.com/88729/93662366-e17b1b00-fa5f-11ea-8fb6-0c6ff5692186.png)

C'est pareil pour tous les devoirs que j'ai vérifié. Est-ce qu'il y a quelque chose que je ne comprend pas dans la logique?

Aussi, la démo référence 2 élèves (Fanny et Manon) mais "session" semble ne contenir que les informations de Fanny. Est-ce que cette API ne supporte qu'un seul élève? (j'aurais peut-être du ouvrir une autre issue pour ça).

Merci

**Comment by Androz2091** [comment]
Bonjour,
Ce résultat est en fait correct. Il vient du fait que Pronote sélectionne par défaut l'onglet `Contenu et ressources` lorsque vous cliquez sur `Cahier de texte` (pas super pratique, mais bon...). Vous pouvez utiliser `session.contents()` pour accéder aux contenus de votre capture d'écran.

**Comment by JBX028** [comment]
ah oui en effet je n'avais pas fait attention. Bon cette fois je pense que je suis ok pour les devoirs.
Et au sujet de ma deuxième remarque sur le nombre d'enfants du site de demo vs l'api?

**Comment by trmaud** [comment]
@JBX028 tu est sur quel partie de l'api ?
Car actuellement il y a que les compte enfant de fait,
Et la branche account gère les compte parent, mais la tu doit preciser l'enfant avec son nom (Compris dans la session)

Cdt
Thibaut

**Comment by Litarvan** [comment]
sur la branche litarvan/accounts tu as les comptes parents avec un tableau students et tu peux préciser l'élève dans chaque requête :)

**Comment by JBX028** [comment]
Bonjour,
Merci. Je vais lire le code source car pour l'instant j'ai seulement joué avec les exemples donnés dans readme.
